/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MenuPrincipalImport } from './routes/menu-principal'
import { Route as LoginImport } from './routes/login'
import { Route as RadiologyImport } from './routes/_radiology'
import { Route as OpdImport } from './routes/_opd'
import { Route as NurseImport } from './routes/_nurse'
import { Route as MedicalStockImport } from './routes/_medical-stock'
import { Route as LabImport } from './routes/_lab'
import { Route as IpdImport } from './routes/_ipd'
import { Route as HomeImport } from './routes/_home'
import { Route as DoctorImport } from './routes/_doctor'
import { Route as AppointmentsImport } from './routes/_appointments'
import { Route as IndexImport } from './routes/index'
import { Route as RadiologyRadiologyImport } from './routes/_radiology/radiology'
import { Route as OpdVaccinImport } from './routes/_opd/vaccin'
import { Route as OpdSettingOpdImport } from './routes/_opd/setting-opd'
import { Route as OpdRevisitImport } from './routes/_opd/revisit'
import { Route as OpdRegistrationOpdImport } from './routes/_opd/registration-opd'
import { Route as OpdQueueImport } from './routes/_opd/queue'
import { Route as OpdProfilOpdImport } from './routes/_opd/profil-opd'
import { Route as OpdMessageOpdImport } from './routes/_opd/message-opd'
import { Route as OpdInvestigationOpdImport } from './routes/_opd/investigation-opd'
import { Route as OpdDayCareImport } from './routes/_opd/dayCare'
import { Route as OpdCertificateImport } from './routes/_opd/certificate'
import { Route as OpdBirthRegistrationImport } from './routes/_opd/birth-registration'
import { Route as NurseNurseImport } from './routes/_nurse/nurse'
import { Route as MedicalStockMedicalStockImport } from './routes/_medical-stock/medical-stock'
import { Route as LabLabImport } from './routes/_lab/lab'
import { Route as IpdReportIpdImport } from './routes/_ipd/report-ipd'
import { Route as IpdRegistrationIpdImport } from './routes/_ipd/registration-ipd'
import { Route as IpdPaymentImport } from './routes/_ipd/payment'
import { Route as IpdOTImport } from './routes/_ipd/oT'
import { Route as IpdMedecinesImport } from './routes/_ipd/medecines'
import { Route as IpdIpdImport } from './routes/_ipd/ipd'
import { Route as IpdInvestigationImport } from './routes/_ipd/investigation'
import { Route as IpdDischargeImport } from './routes/_ipd/discharge'
import { Route as HomeSettingImport } from './routes/_home/setting'
import { Route as HomeServiceImport } from './routes/_home/service'
import { Route as HomeReportImport } from './routes/_home/report'
import { Route as HomeProfilImport } from './routes/_home/profil'
import { Route as HomePersonnelImport } from './routes/_home/personnel'
import { Route as HomePatientImport } from './routes/_home/patient'
import { Route as HomeMessageImport } from './routes/_home/message'
import { Route as HomeDashboardImport } from './routes/_home/dashboard'
import { Route as DoctorSettingDoctorImport } from './routes/_doctor/setting-doctor'
import { Route as DoctorProfilDoctorImport } from './routes/_doctor/profil-doctor'
import { Route as DoctorMessageDoctorImport } from './routes/_doctor/message-doctor'
import { Route as DoctorDashboardDoctorImport} from './routes/_doctor/dashboard-doctor'
import { Route as AppointmentsSuiviAppointmentImport } from './routes/_appointments/suiviAppointment'
import { Route as AppointmentsSettingAppointmentImport } from './routes/_appointments/setting-appointment'
import { Route as AppointmentsProfilAppointmentImport } from './routes/_appointments/profil-appointment'
import { Route as AppointmentsPriseAppointmentImport } from './routes/_appointments/priseAppointment'
import { Route as AppointmentsMessageAppointmentImport } from './routes/_appointments/message-appointment'
import { Route as AppointmentsDashboardAppointmentImport } from './routes/_appointments/dashboard-appointment'

// Create/Update Routes

const MenuPrincipalRoute = MenuPrincipalImport.update({
  id: '/menu-principal',
  path: '/menu-principal',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const RadiologyRoute = RadiologyImport.update({
  id: '/_radiology',
  getParentRoute: () => rootRoute,
} as any)

const OpdRoute = OpdImport.update({
  id: '/_opd',
  getParentRoute: () => rootRoute,
} as any)

const NurseRoute = NurseImport.update({
  id: '/_nurse',
  getParentRoute: () => rootRoute,
} as any)

const MedicalStockRoute = MedicalStockImport.update({
  id: '/_medical-stock',
  getParentRoute: () => rootRoute,
} as any)

const LabRoute = LabImport.update({
  id: '/_lab',
  getParentRoute: () => rootRoute,
} as any)

const IpdRoute = IpdImport.update({
  id: '/_ipd',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const DoctorRoute = DoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentsRoute = AppointmentsImport.update({
  id: '/_appointments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RadiologyRadiologyRoute = RadiologyRadiologyImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => RadiologyRoute,
} as any)

const OpdVaccinRoute = OpdVaccinImport.update({
  id: '/vaccin',
  path: '/vaccin',
  getParentRoute: () => OpdRoute,
} as any)

const OpdSettingOpdRoute = OpdSettingOpdImport.update({
  id: '/setting-opd',
  path: '/setting-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdRevisitRoute = OpdRevisitImport.update({
  id: '/revisit',
  path: '/revisit',
  getParentRoute: () => OpdRoute,
} as any)

const OpdRegistrationOpdRoute = OpdRegistrationOpdImport.update({
  id: '/registration-opd',
  path: '/registration-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdQueueRoute = OpdQueueImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OpdRoute,
} as any)

const OpdProfilOpdRoute = OpdProfilOpdImport.update({
  id: '/profil-opd',
  path: '/profil-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdMessageOpdRoute = OpdMessageOpdImport.update({
  id: '/message-opd',
  path: '/message-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdInvestigationOpdRoute = OpdInvestigationOpdImport.update({
  id: '/investigation-opd',
  path: '/investigation-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdDayCareRoute = OpdDayCareImport.update({
  id: '/dayCare',
  path: '/dayCare',
  getParentRoute: () => OpdRoute,
} as any)

const OpdCertificateRoute = OpdCertificateImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => OpdRoute,
} as any)

const OpdBirthRegistrationRoute = OpdBirthRegistrationImport.update({
  id: '/birth-registration',
  path: '/birth-registration',
  getParentRoute: () => OpdRoute,
} as any)

const NurseNurseRoute = NurseNurseImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => NurseRoute,
} as any)

const MedicalStockMedicalStockRoute = MedicalStockMedicalStockImport.update({
  id: '/medical-stock',
  path: '/medical-stock',
  getParentRoute: () => MedicalStockRoute,
} as any)

const LabLabRoute = LabLabImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => LabRoute,
} as any)

const IpdReportIpdRoute = IpdReportIpdImport.update({
  id: '/report-ipd',
  path: '/report-ipd',
  getParentRoute: () => IpdRoute,
} as any)

const IpdRegistrationIpdRoute = IpdRegistrationIpdImport.update({
  id: '/registration-ipd',
  path: '/registration-ipd',
  getParentRoute: () => IpdRoute,
} as any)

const IpdPaymentRoute = IpdPaymentImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => IpdRoute,
} as any)

const IpdOTRoute = IpdOTImport.update({
  id: '/oT',
  path: '/oT',
  getParentRoute: () => IpdRoute,
} as any)

const IpdMedecinesRoute = IpdMedecinesImport.update({
  id: '/medecines',
  path: '/medecines',
  getParentRoute: () => IpdRoute,
} as any)

const IpdIpdRoute = IpdIpdImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => IpdRoute,
} as any)

const IpdInvestigationRoute = IpdInvestigationImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => IpdRoute,
} as any)

const IpdDischargeRoute = IpdDischargeImport.update({
  id: '/discharge',
  path: '/discharge',
  getParentRoute: () => IpdRoute,
} as any)

const HomeSettingRoute = HomeSettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => HomeRoute,
} as any)

const HomeServiceRoute = HomeServiceImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => HomeRoute,
} as any)

const HomeReportRoute = HomeReportImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => HomeRoute,
} as any)

const HomeProfilRoute = HomeProfilImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => HomeRoute,
} as any)

const HomePersonnelRoute = HomePersonnelImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => HomeRoute,
} as any)

const HomePatientRoute = HomePatientImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => HomeRoute,
} as any)

const HomeMessageRoute = HomeMessageImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDashboardRoute = HomeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRoute,
} as any)

const DoctorSettingDoctorRoute = DoctorSettingDoctorImport.update({
  id: '/setting-doctor',
  path: '/setting-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorProfilDoctorRoute = DoctorProfilDoctorImport.update({
  id: '/profil-doctor',
  path: '/profil-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorMessageDoctorRoute = DoctorMessageDoctorImport.update({
  id: '/message-doctor',
  path: '/message-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorDashboardDoctorRoute = DoctorDashboardDoctorImport.update({
  id: '/dashboard-doctor',
  path: '/dashboard-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const AppointmentsSuiviAppointmentRoute =
  AppointmentsSuiviAppointmentImport.update({
    id: '/suiviAppointment',
    path: '/suiviAppointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsSettingAppointmentRoute =
  AppointmentsSettingAppointmentImport.update({
    id: '/setting-appointment',
    path: '/setting-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsProfilAppointmentRoute =
  AppointmentsProfilAppointmentImport.update({
    id: '/profil-appointment',
    path: '/profil-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsPriseAppointmentRoute =
  AppointmentsPriseAppointmentImport.update({
    id: '/priseAppointment',
    path: '/priseAppointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsMessageAppointmentRoute =
  AppointmentsMessageAppointmentImport.update({
    id: '/message-appointment',
    path: '/message-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsDashboardAppointmentRoute =
  AppointmentsDashboardAppointmentImport.update({
    id: '/dashboard-appointment',
    path: '/dashboard-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_appointments': {
      id: '/_appointments'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppointmentsImport
      parentRoute: typeof rootRoute
    }
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DoctorImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_ipd': {
      id: '/_ipd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IpdImport
      parentRoute: typeof rootRoute
    }
    '/_lab': {
      id: '/_lab'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LabImport
      parentRoute: typeof rootRoute
    }
    '/_medical-stock': {
      id: '/_medical-stock'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MedicalStockImport
      parentRoute: typeof rootRoute
    }
    '/_nurse': {
      id: '/_nurse'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NurseImport
      parentRoute: typeof rootRoute
    }
    '/_opd': {
      id: '/_opd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OpdImport
      parentRoute: typeof rootRoute
    }
    '/_radiology': {
      id: '/_radiology'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RadiologyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/menu-principal': {
      id: '/menu-principal'
      path: '/menu-principal'
      fullPath: '/menu-principal'
      preLoaderRoute: typeof MenuPrincipalImport
      parentRoute: typeof rootRoute
    }
    '/_appointments/dashboard-appointment': {
      id: '/_appointments/dashboard-appointment'
      path: '/dashboard-appointment'
      fullPath: '/dashboard-appointment'
      preLoaderRoute: typeof AppointmentsDashboardAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/message-appointment': {
      id: '/_appointments/message-appointment'
      path: '/message-appointment'
      fullPath: '/message-appointment'
      preLoaderRoute: typeof AppointmentsMessageAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/priseAppointment': {
      id: '/_appointments/priseAppointment'
      path: '/priseAppointment'
      fullPath: '/priseAppointment'
      preLoaderRoute: typeof AppointmentsPriseAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/profil-appointment': {
      id: '/_appointments/profil-appointment'
      path: '/profil-appointment'
      fullPath: '/profil-appointment'
      preLoaderRoute: typeof AppointmentsProfilAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/setting-appointment': {
      id: '/_appointments/setting-appointment'
      path: '/setting-appointment'
      fullPath: '/setting-appointment'
      preLoaderRoute: typeof AppointmentsSettingAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/suiviAppointment': {
      id: '/_appointments/suiviAppointment'
      path: '/suiviAppointment'
      fullPath: '/suiviAppointment'
      preLoaderRoute: typeof AppointmentsSuiviAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_doctor/dashboard-doctor': {
      id: '/_doctor/dashboard-doctor'
      path: '/dashboard-doctor'
      fullPath: '/dashboard-doctor'
      preLoaderRoute: typeof DoctorDashboardDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/message-doctor': {
      id: '/_doctor/message-doctor'
      path: '/message-doctor'
      fullPath: '/message-doctor'
      preLoaderRoute: typeof DoctorMessageDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/profil-doctor': {
      id: '/_doctor/profil-doctor'
      path: '/profil-doctor'
      fullPath: '/profil-doctor'
      preLoaderRoute: typeof DoctorProfilDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/setting-doctor': {
      id: '/_doctor/setting-doctor'
      path: '/setting-doctor'
      fullPath: '/setting-doctor'
      preLoaderRoute: typeof DoctorSettingDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_home/dashboard': {
      id: '/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HomeDashboardImport
      parentRoute: typeof HomeImport
    }
    '/_home/message': {
      id: '/_home/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof HomeMessageImport
      parentRoute: typeof HomeImport
    }
    '/_home/patient': {
      id: '/_home/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof HomePatientImport
      parentRoute: typeof HomeImport
    }
    '/_home/personnel': {
      id: '/_home/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof HomePersonnelImport
      parentRoute: typeof HomeImport
    }
    '/_home/profil': {
      id: '/_home/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof HomeProfilImport
      parentRoute: typeof HomeImport
    }
    '/_home/report': {
      id: '/_home/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof HomeReportImport
      parentRoute: typeof HomeImport
    }
    '/_home/service': {
      id: '/_home/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof HomeServiceImport
      parentRoute: typeof HomeImport
    }
    '/_home/setting': {
      id: '/_home/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof HomeSettingImport
      parentRoute: typeof HomeImport
    }
    '/_ipd/discharge': {
      id: '/_ipd/discharge'
      path: '/discharge'
      fullPath: '/discharge'
      preLoaderRoute: typeof IpdDischargeImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/investigation': {
      id: '/_ipd/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof IpdInvestigationImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/ipd': {
      id: '/_ipd/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof IpdIpdImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/medecines': {
      id: '/_ipd/medecines'
      path: '/medecines'
      fullPath: '/medecines'
      preLoaderRoute: typeof IpdMedecinesImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/oT': {
      id: '/_ipd/oT'
      path: '/oT'
      fullPath: '/oT'
      preLoaderRoute: typeof IpdOTImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/payment': {
      id: '/_ipd/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof IpdPaymentImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/registration-ipd': {
      id: '/_ipd/registration-ipd'
      path: '/registration-ipd'
      fullPath: '/registration-ipd'
      preLoaderRoute: typeof IpdRegistrationIpdImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/report-ipd': {
      id: '/_ipd/report-ipd'
      path: '/report-ipd'
      fullPath: '/report-ipd'
      preLoaderRoute: typeof IpdReportIpdImport
      parentRoute: typeof IpdImport
    }
    '/_lab/lab': {
      id: '/_lab/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabLabImport
      parentRoute: typeof LabImport
    }
    '/_medical-stock/medical-stock': {
      id: '/_medical-stock/medical-stock'
      path: '/medical-stock'
      fullPath: '/medical-stock'
      preLoaderRoute: typeof MedicalStockMedicalStockImport
      parentRoute: typeof MedicalStockImport
    }
    '/_nurse/nurse': {
      id: '/_nurse/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseNurseImport
      parentRoute: typeof NurseImport
    }
    '/_opd/birth-registration': {
      id: '/_opd/birth-registration'
      path: '/birth-registration'
      fullPath: '/birth-registration'
      preLoaderRoute: typeof OpdBirthRegistrationImport
      parentRoute: typeof OpdImport
    }
    '/_opd/certificate': {
      id: '/_opd/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof OpdCertificateImport
      parentRoute: typeof OpdImport
    }
    '/_opd/dayCare': {
      id: '/_opd/dayCare'
      path: '/dayCare'
      fullPath: '/dayCare'
      preLoaderRoute: typeof OpdDayCareImport
      parentRoute: typeof OpdImport
    }
    '/_opd/investigation-opd': {
      id: '/_opd/investigation-opd'
      path: '/investigation-opd'
      fullPath: '/investigation-opd'
      preLoaderRoute: typeof OpdInvestigationOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/message-opd': {
      id: '/_opd/message-opd'
      path: '/message-opd'
      fullPath: '/message-opd'
      preLoaderRoute: typeof OpdMessageOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/profil-opd': {
      id: '/_opd/profil-opd'
      path: '/profil-opd'
      fullPath: '/profil-opd'
      preLoaderRoute: typeof OpdProfilOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/queue': {
      id: '/_opd/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof OpdQueueImport
      parentRoute: typeof OpdImport
    }
    '/_opd/registration-opd': {
      id: '/_opd/registration-opd'
      path: '/registration-opd'
      fullPath: '/registration-opd'
      preLoaderRoute: typeof OpdRegistrationOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/revisit': {
      id: '/_opd/revisit'
      path: '/revisit'
      fullPath: '/revisit'
      preLoaderRoute: typeof OpdRevisitImport
      parentRoute: typeof OpdImport
    }
    '/_opd/setting-opd': {
      id: '/_opd/setting-opd'
      path: '/setting-opd'
      fullPath: '/setting-opd'
      preLoaderRoute: typeof OpdSettingOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/vaccin': {
      id: '/_opd/vaccin'
      path: '/vaccin'
      fullPath: '/vaccin'
      preLoaderRoute: typeof OpdVaccinImport
      parentRoute: typeof OpdImport
    }
    '/_radiology/radiology': {
      id: '/_radiology/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRadiologyImport
      parentRoute: typeof RadiologyImport
    }
  }
}

// Create and export the route tree

interface AppointmentsRouteChildren {
  AppointmentsDashboardAppointmentRoute: typeof AppointmentsDashboardAppointmentRoute
  AppointmentsMessageAppointmentRoute: typeof AppointmentsMessageAppointmentRoute
  AppointmentsPriseAppointmentRoute: typeof AppointmentsPriseAppointmentRoute
  AppointmentsProfilAppointmentRoute: typeof AppointmentsProfilAppointmentRoute
  AppointmentsSettingAppointmentRoute: typeof AppointmentsSettingAppointmentRoute
  AppointmentsSuiviAppointmentRoute: typeof AppointmentsSuiviAppointmentRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsDashboardAppointmentRoute: AppointmentsDashboardAppointmentRoute,
  AppointmentsMessageAppointmentRoute: AppointmentsMessageAppointmentRoute,
  AppointmentsPriseAppointmentRoute: AppointmentsPriseAppointmentRoute,
  AppointmentsProfilAppointmentRoute: AppointmentsProfilAppointmentRoute,
  AppointmentsSettingAppointmentRoute: AppointmentsSettingAppointmentRoute,
  AppointmentsSuiviAppointmentRoute: AppointmentsSuiviAppointmentRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorDashboardDoctorRoute: typeof DoctorDashboardDoctorRoute
  DoctorMessageDoctorRoute: typeof DoctorMessageDoctorRoute
  DoctorProfilDoctorRoute: typeof DoctorProfilDoctorRoute
  DoctorSettingDoctorRoute: typeof DoctorSettingDoctorRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorDashboardDoctorRoute: DoctorDashboardDoctorRoute,
  DoctorMessageDoctorRoute: DoctorMessageDoctorRoute,
  DoctorProfilDoctorRoute: DoctorProfilDoctorRoute,
  DoctorSettingDoctorRoute: DoctorSettingDoctorRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface HomeRouteChildren {
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeMessageRoute: typeof HomeMessageRoute
  HomePatientRoute: typeof HomePatientRoute
  HomePersonnelRoute: typeof HomePersonnelRoute
  HomeProfilRoute: typeof HomeProfilRoute
  HomeReportRoute: typeof HomeReportRoute
  HomeServiceRoute: typeof HomeServiceRoute
  HomeSettingRoute: typeof HomeSettingRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeDashboardRoute: HomeDashboardRoute,
  HomeMessageRoute: HomeMessageRoute,
  HomePatientRoute: HomePatientRoute,
  HomePersonnelRoute: HomePersonnelRoute,
  HomeProfilRoute: HomeProfilRoute,
  HomeReportRoute: HomeReportRoute,
  HomeServiceRoute: HomeServiceRoute,
  HomeSettingRoute: HomeSettingRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface IpdRouteChildren {
  IpdDischargeRoute: typeof IpdDischargeRoute
  IpdInvestigationRoute: typeof IpdInvestigationRoute
  IpdIpdRoute: typeof IpdIpdRoute
  IpdMedecinesRoute: typeof IpdMedecinesRoute
  IpdOTRoute: typeof IpdOTRoute
  IpdPaymentRoute: typeof IpdPaymentRoute
  IpdRegistrationIpdRoute: typeof IpdRegistrationIpdRoute
  IpdReportIpdRoute: typeof IpdReportIpdRoute
}

const IpdRouteChildren: IpdRouteChildren = {
  IpdDischargeRoute: IpdDischargeRoute,
  IpdInvestigationRoute: IpdInvestigationRoute,
  IpdIpdRoute: IpdIpdRoute,
  IpdMedecinesRoute: IpdMedecinesRoute,
  IpdOTRoute: IpdOTRoute,
  IpdPaymentRoute: IpdPaymentRoute,
  IpdRegistrationIpdRoute: IpdRegistrationIpdRoute,
  IpdReportIpdRoute: IpdReportIpdRoute,
}

const IpdRouteWithChildren = IpdRoute._addFileChildren(IpdRouteChildren)

interface LabRouteChildren {
  LabLabRoute: typeof LabLabRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabLabRoute: LabLabRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface MedicalStockRouteChildren {
  MedicalStockMedicalStockRoute: typeof MedicalStockMedicalStockRoute
}

const MedicalStockRouteChildren: MedicalStockRouteChildren = {
  MedicalStockMedicalStockRoute: MedicalStockMedicalStockRoute,
}

const MedicalStockRouteWithChildren = MedicalStockRoute._addFileChildren(
  MedicalStockRouteChildren,
)

interface NurseRouteChildren {
  NurseNurseRoute: typeof NurseNurseRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseNurseRoute: NurseNurseRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface OpdRouteChildren {
  OpdBirthRegistrationRoute: typeof OpdBirthRegistrationRoute
  OpdCertificateRoute: typeof OpdCertificateRoute
  OpdDayCareRoute: typeof OpdDayCareRoute
  OpdInvestigationOpdRoute: typeof OpdInvestigationOpdRoute
  OpdMessageOpdRoute: typeof OpdMessageOpdRoute
  OpdProfilOpdRoute: typeof OpdProfilOpdRoute
  OpdQueueRoute: typeof OpdQueueRoute
  OpdRegistrationOpdRoute: typeof OpdRegistrationOpdRoute
  OpdRevisitRoute: typeof OpdRevisitRoute
  OpdSettingOpdRoute: typeof OpdSettingOpdRoute
  OpdVaccinRoute: typeof OpdVaccinRoute
}

const OpdRouteChildren: OpdRouteChildren = {
  OpdBirthRegistrationRoute: OpdBirthRegistrationRoute,
  OpdCertificateRoute: OpdCertificateRoute,
  OpdDayCareRoute: OpdDayCareRoute,
  OpdInvestigationOpdRoute: OpdInvestigationOpdRoute,
  OpdMessageOpdRoute: OpdMessageOpdRoute,
  OpdProfilOpdRoute: OpdProfilOpdRoute,
  OpdQueueRoute: OpdQueueRoute,
  OpdRegistrationOpdRoute: OpdRegistrationOpdRoute,
  OpdRevisitRoute: OpdRevisitRoute,
  OpdSettingOpdRoute: OpdSettingOpdRoute,
  OpdVaccinRoute: OpdVaccinRoute,
}

const OpdRouteWithChildren = OpdRoute._addFileChildren(OpdRouteChildren)

interface RadiologyRouteChildren {
  RadiologyRadiologyRoute: typeof RadiologyRadiologyRoute
}

const RadiologyRouteChildren: RadiologyRouteChildren = {
  RadiologyRadiologyRoute: RadiologyRadiologyRoute,
}

const RadiologyRouteWithChildren = RadiologyRoute._addFileChildren(
  RadiologyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof RadiologyRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/dashboard-appointment': typeof AppointmentsDashboardAppointmentRoute
  '/message-appointment': typeof AppointmentsMessageAppointmentRoute
  '/priseAppointment': typeof AppointmentsPriseAppointmentRoute
  '/profil-appointment': typeof AppointmentsProfilAppointmentRoute
  '/setting-appointment': typeof AppointmentsSettingAppointmentRoute
  '/suiviAppointment': typeof AppointmentsSuiviAppointmentRoute
  '/dashboard-doctor': typeof DoctorDashboardDoctorRoute
  '/message-doctor': typeof DoctorMessageDoctorRoute
  '/profil-doctor': typeof DoctorProfilDoctorRoute
  '/setting-doctor': typeof DoctorSettingDoctorRoute
  '/dashboard': typeof HomeDashboardRoute
  '/message': typeof HomeMessageRoute
  '/patient': typeof HomePatientRoute
  '/personnel': typeof HomePersonnelRoute
  '/profil': typeof HomeProfilRoute
  '/report': typeof HomeReportRoute
  '/service': typeof HomeServiceRoute
  '/setting': typeof HomeSettingRoute
  '/discharge': typeof IpdDischargeRoute
  '/investigation': typeof IpdInvestigationRoute
  '/ipd': typeof IpdIpdRoute
  '/medecines': typeof IpdMedecinesRoute
  '/oT': typeof IpdOTRoute
  '/payment': typeof IpdPaymentRoute
  '/registration-ipd': typeof IpdRegistrationIpdRoute
  '/report-ipd': typeof IpdReportIpdRoute
  '/lab': typeof LabLabRoute
  '/medical-stock': typeof MedicalStockMedicalStockRoute
  '/nurse': typeof NurseNurseRoute
  '/birth-registration': typeof OpdBirthRegistrationRoute
  '/certificate': typeof OpdCertificateRoute
  '/dayCare': typeof OpdDayCareRoute
  '/investigation-opd': typeof OpdInvestigationOpdRoute
  '/message-opd': typeof OpdMessageOpdRoute
  '/profil-opd': typeof OpdProfilOpdRoute
  '/queue': typeof OpdQueueRoute
  '/registration-opd': typeof OpdRegistrationOpdRoute
  '/revisit': typeof OpdRevisitRoute
  '/setting-opd': typeof OpdSettingOpdRoute
  '/vaccin': typeof OpdVaccinRoute
  '/radiology': typeof RadiologyRadiologyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof RadiologyRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/dashboard-appointment': typeof AppointmentsDashboardAppointmentRoute
  '/message-appointment': typeof AppointmentsMessageAppointmentRoute
  '/priseAppointment': typeof AppointmentsPriseAppointmentRoute
  '/profil-appointment': typeof AppointmentsProfilAppointmentRoute
  '/setting-appointment': typeof AppointmentsSettingAppointmentRoute
  '/suiviAppointment': typeof AppointmentsSuiviAppointmentRoute
  '/dashboard-doctor': typeof DoctorDashboardDoctorRoute
  '/message-doctor': typeof DoctorMessageDoctorRoute
  '/profil-doctor': typeof DoctorProfilDoctorRoute
  '/setting-doctor': typeof DoctorSettingDoctorRoute
  '/dashboard': typeof HomeDashboardRoute
  '/message': typeof HomeMessageRoute
  '/patient': typeof HomePatientRoute
  '/personnel': typeof HomePersonnelRoute
  '/profil': typeof HomeProfilRoute
  '/report': typeof HomeReportRoute
  '/service': typeof HomeServiceRoute
  '/setting': typeof HomeSettingRoute
  '/discharge': typeof IpdDischargeRoute
  '/investigation': typeof IpdInvestigationRoute
  '/ipd': typeof IpdIpdRoute
  '/medecines': typeof IpdMedecinesRoute
  '/oT': typeof IpdOTRoute
  '/payment': typeof IpdPaymentRoute
  '/registration-ipd': typeof IpdRegistrationIpdRoute
  '/report-ipd': typeof IpdReportIpdRoute
  '/lab': typeof LabLabRoute
  '/medical-stock': typeof MedicalStockMedicalStockRoute
  '/nurse': typeof NurseNurseRoute
  '/birth-registration': typeof OpdBirthRegistrationRoute
  '/certificate': typeof OpdCertificateRoute
  '/dayCare': typeof OpdDayCareRoute
  '/investigation-opd': typeof OpdInvestigationOpdRoute
  '/message-opd': typeof OpdMessageOpdRoute
  '/profil-opd': typeof OpdProfilOpdRoute
  '/queue': typeof OpdQueueRoute
  '/registration-opd': typeof OpdRegistrationOpdRoute
  '/revisit': typeof OpdRevisitRoute
  '/setting-opd': typeof OpdSettingOpdRoute
  '/vaccin': typeof OpdVaccinRoute
  '/radiology': typeof RadiologyRadiologyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_appointments': typeof AppointmentsRouteWithChildren
  '/_doctor': typeof DoctorRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_ipd': typeof IpdRouteWithChildren
  '/_lab': typeof LabRouteWithChildren
  '/_medical-stock': typeof MedicalStockRouteWithChildren
  '/_nurse': typeof NurseRouteWithChildren
  '/_opd': typeof OpdRouteWithChildren
  '/_radiology': typeof RadiologyRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/_appointments/dashboard-appointment': typeof AppointmentsDashboardAppointmentRoute
  '/_appointments/message-appointment': typeof AppointmentsMessageAppointmentRoute
  '/_appointments/priseAppointment': typeof AppointmentsPriseAppointmentRoute
  '/_appointments/profil-appointment': typeof AppointmentsProfilAppointmentRoute
  '/_appointments/setting-appointment': typeof AppointmentsSettingAppointmentRoute
  '/_appointments/suiviAppointment': typeof AppointmentsSuiviAppointmentRoute
  '/_doctor/dashboard-doctor': typeof DoctorDashboardDoctorRoute
  '/_doctor/message-doctor': typeof DoctorMessageDoctorRoute
  '/_doctor/profil-doctor': typeof DoctorProfilDoctorRoute
  '/_doctor/setting-doctor': typeof DoctorSettingDoctorRoute
  '/_home/dashboard': typeof HomeDashboardRoute
  '/_home/message': typeof HomeMessageRoute
  '/_home/patient': typeof HomePatientRoute
  '/_home/personnel': typeof HomePersonnelRoute
  '/_home/profil': typeof HomeProfilRoute
  '/_home/report': typeof HomeReportRoute
  '/_home/service': typeof HomeServiceRoute
  '/_home/setting': typeof HomeSettingRoute
  '/_ipd/discharge': typeof IpdDischargeRoute
  '/_ipd/investigation': typeof IpdInvestigationRoute
  '/_ipd/ipd': typeof IpdIpdRoute
  '/_ipd/medecines': typeof IpdMedecinesRoute
  '/_ipd/oT': typeof IpdOTRoute
  '/_ipd/payment': typeof IpdPaymentRoute
  '/_ipd/registration-ipd': typeof IpdRegistrationIpdRoute
  '/_ipd/report-ipd': typeof IpdReportIpdRoute
  '/_lab/lab': typeof LabLabRoute
  '/_medical-stock/medical-stock': typeof MedicalStockMedicalStockRoute
  '/_nurse/nurse': typeof NurseNurseRoute
  '/_opd/birth-registration': typeof OpdBirthRegistrationRoute
  '/_opd/certificate': typeof OpdCertificateRoute
  '/_opd/dayCare': typeof OpdDayCareRoute
  '/_opd/investigation-opd': typeof OpdInvestigationOpdRoute
  '/_opd/message-opd': typeof OpdMessageOpdRoute
  '/_opd/profil-opd': typeof OpdProfilOpdRoute
  '/_opd/queue': typeof OpdQueueRoute
  '/_opd/registration-opd': typeof OpdRegistrationOpdRoute
  '/_opd/revisit': typeof OpdRevisitRoute
  '/_opd/setting-opd': typeof OpdSettingOpdRoute
  '/_opd/vaccin': typeof OpdVaccinRoute
  '/_radiology/radiology': typeof RadiologyRadiologyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/menu-principal'
    | '/dashboard-appointment'
    | '/message-appointment'
    | '/priseAppointment'
    | '/profil-appointment'
    | '/setting-appointment'
    | '/suiviAppointment'
    | '/dashboard-doctor'
    | '/message-doctor'
    | '/profil-doctor'
    | '/setting-doctor'
    | '/dashboard'
    | '/message'
    | '/patient'
    | '/personnel'
    | '/profil'
    | '/report'
    | '/service'
    | '/setting'
    | '/discharge'
    | '/investigation'
    | '/ipd'
    | '/medecines'
    | '/oT'
    | '/payment'
    | '/registration-ipd'
    | '/report-ipd'
    | '/lab'
    | '/medical-stock'
    | '/nurse'
    | '/birth-registration'
    | '/certificate'
    | '/dayCare'
    | '/investigation-opd'
    | '/message-opd'
    | '/profil-opd'
    | '/queue'
    | '/registration-opd'
    | '/revisit'
    | '/setting-opd'
    | '/vaccin'
    | '/radiology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/menu-principal'
    | '/dashboard-appointment'
    | '/message-appointment'
    | '/priseAppointment'
    | '/profil-appointment'
    | '/setting-appointment'
    | '/suiviAppointment'
    | '/dashboard-doctor'
    | '/message-doctor'
    | '/profil-doctor'
    | '/setting-doctor'
    | '/dashboard'
    | '/message'
    | '/patient'
    | '/personnel'
    | '/profil'
    | '/report'
    | '/service'
    | '/setting'
    | '/discharge'
    | '/investigation'
    | '/ipd'
    | '/medecines'
    | '/oT'
    | '/payment'
    | '/registration-ipd'
    | '/report-ipd'
    | '/lab'
    | '/medical-stock'
    | '/nurse'
    | '/birth-registration'
    | '/certificate'
    | '/dayCare'
    | '/investigation-opd'
    | '/message-opd'
    | '/profil-opd'
    | '/queue'
    | '/registration-opd'
    | '/revisit'
    | '/setting-opd'
    | '/vaccin'
    | '/radiology'
  id:
    | '__root__'
    | '/'
    | '/_appointments'
    | '/_doctor'
    | '/_home'
    | '/_ipd'
    | '/_lab'
    | '/_medical-stock'
    | '/_nurse'
    | '/_opd'
    | '/_radiology'
    | '/login'
    | '/menu-principal'
    | '/_appointments/dashboard-appointment'
    | '/_appointments/message-appointment'
    | '/_appointments/priseAppointment'
    | '/_appointments/profil-appointment'
    | '/_appointments/setting-appointment'
    | '/_appointments/suiviAppointment'
    | '/_doctor/dashboard-doctor'
    | '/_doctor/message-doctor'
    | '/_doctor/profil-doctor'
    | '/_doctor/setting-doctor'
    | '/_home/dashboard'
    | '/_home/message'
    | '/_home/patient'
    | '/_home/personnel'
    | '/_home/profil'
    | '/_home/report'
    | '/_home/service'
    | '/_home/setting'
    | '/_ipd/discharge'
    | '/_ipd/investigation'
    | '/_ipd/ipd'
    | '/_ipd/medecines'
    | '/_ipd/oT'
    | '/_ipd/payment'
    | '/_ipd/registration-ipd'
    | '/_ipd/report-ipd'
    | '/_lab/lab'
    | '/_medical-stock/medical-stock'
    | '/_nurse/nurse'
    | '/_opd/birth-registration'
    | '/_opd/certificate'
    | '/_opd/dayCare'
    | '/_opd/investigation-opd'
    | '/_opd/message-opd'
    | '/_opd/profil-opd'
    | '/_opd/queue'
    | '/_opd/registration-opd'
    | '/_opd/revisit'
    | '/_opd/setting-opd'
    | '/_opd/vaccin'
    | '/_radiology/radiology'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  IpdRoute: typeof IpdRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  MedicalStockRoute: typeof MedicalStockRouteWithChildren
  NurseRoute: typeof NurseRouteWithChildren
  OpdRoute: typeof OpdRouteWithChildren
  RadiologyRoute: typeof RadiologyRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuPrincipalRoute: typeof MenuPrincipalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  IpdRoute: IpdRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  MedicalStockRoute: MedicalStockRouteWithChildren,
  NurseRoute: NurseRouteWithChildren,
  OpdRoute: OpdRouteWithChildren,
  RadiologyRoute: RadiologyRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuPrincipalRoute: MenuPrincipalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_appointments",
        "/_doctor",
        "/_home",
        "/_ipd",
        "/_lab",
        "/_medical-stock",
        "/_nurse",
        "/_opd",
        "/_radiology",
        "/login",
        "/menu-principal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_appointments": {
      "filePath": "_appointments.tsx",
      "children": [
        "/_appointments/dashboard-appointment",
        "/_appointments/message-appointment",
        "/_appointments/priseAppointment",
        "/_appointments/profil-appointment",
        "/_appointments/setting-appointment",
        "/_appointments/suiviAppointment"
      ]
    },
    "/_doctor": {
      "filePath": "_doctor.tsx",
      "children": [
        "/_doctor/dashboard-doctor",
        "/_doctor/message-doctor",
        "/_doctor/profil-doctor",
        "/_doctor/setting-doctor"
      ]
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/dashboard",
        "/_home/message",
        "/_home/patient",
        "/_home/personnel",
        "/_home/profil",
        "/_home/report",
        "/_home/service",
        "/_home/setting"
      ]
    },
    "/_ipd": {
      "filePath": "_ipd.tsx",
      "children": [
        "/_ipd/discharge",
        "/_ipd/investigation",
        "/_ipd/ipd",
        "/_ipd/medecines",
        "/_ipd/oT",
        "/_ipd/payment",
        "/_ipd/registration-ipd",
        "/_ipd/report-ipd"
      ]
    },
    "/_lab": {
      "filePath": "_lab.tsx",
      "children": [
        "/_lab/lab"
      ]
    },
    "/_medical-stock": {
      "filePath": "_medical-stock.tsx",
      "children": [
        "/_medical-stock/medical-stock"
      ]
    },
    "/_nurse": {
      "filePath": "_nurse.tsx",
      "children": [
        "/_nurse/nurse"
      ]
    },
    "/_opd": {
      "filePath": "_opd.tsx",
      "children": [
        "/_opd/birth-registration",
        "/_opd/certificate",
        "/_opd/dayCare",
        "/_opd/investigation-opd",
        "/_opd/message-opd",
        "/_opd/profil-opd",
        "/_opd/queue",
        "/_opd/registration-opd",
        "/_opd/revisit",
        "/_opd/setting-opd",
        "/_opd/vaccin"
      ]
    },
    "/_radiology": {
      "filePath": "_radiology.tsx",
      "children": [
        "/_radiology/radiology"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/menu-principal": {
      "filePath": "menu-principal.tsx"
    },
    "/_appointments/dashboard-appointment": {
      "filePath": "_appointments/dashboard-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/message-appointment": {
      "filePath": "_appointments/message-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/priseAppointment": {
      "filePath": "_appointments/priseAppointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/profil-appointment": {
      "filePath": "_appointments/profil-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/setting-appointment": {
      "filePath": "_appointments/setting-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/suiviAppointment": {
      "filePath": "_appointments/suiviAppointment.tsx",
      "parent": "/_appointments"
    },
    "/_doctor/dashboard-doctor": {
      "filePath": "_doctor/dashboard-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/message-doctor": {
      "filePath": "_doctor/message-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/profil-doctor": {
      "filePath": "_doctor/profil-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/setting-doctor": {
      "filePath": "_doctor/setting-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_home/dashboard": {
      "filePath": "_home/dashboard.tsx",
      "parent": "/_home"
    },
    "/_home/message": {
      "filePath": "_home/message.tsx",
      "parent": "/_home"
    },
    "/_home/patient": {
      "filePath": "_home/patient.tsx",
      "parent": "/_home"
    },
    "/_home/personnel": {
      "filePath": "_home/personnel.tsx",
      "parent": "/_home"
    },
    "/_home/profil": {
      "filePath": "_home/profil.tsx",
      "parent": "/_home"
    },
    "/_home/report": {
      "filePath": "_home/report.tsx",
      "parent": "/_home"
    },
    "/_home/service": {
      "filePath": "_home/service.tsx",
      "parent": "/_home"
    },
    "/_home/setting": {
      "filePath": "_home/setting.tsx",
      "parent": "/_home"
    },
    "/_ipd/discharge": {
      "filePath": "_ipd/discharge.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/investigation": {
      "filePath": "_ipd/investigation.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/ipd": {
      "filePath": "_ipd/ipd.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/medecines": {
      "filePath": "_ipd/medecines.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/oT": {
      "filePath": "_ipd/oT.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/payment": {
      "filePath": "_ipd/payment.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/registration-ipd": {
      "filePath": "_ipd/registration-ipd.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/report-ipd": {
      "filePath": "_ipd/report-ipd.tsx",
      "parent": "/_ipd"
    },
    "/_lab/lab": {
      "filePath": "_lab/lab.tsx",
      "parent": "/_lab"
    },
    "/_medical-stock/medical-stock": {
      "filePath": "_medical-stock/medical-stock.tsx",
      "parent": "/_medical-stock"
    },
    "/_nurse/nurse": {
      "filePath": "_nurse/nurse.tsx",
      "parent": "/_nurse"
    },
    "/_opd/birth-registration": {
      "filePath": "_opd/birth-registration.tsx",
      "parent": "/_opd"
    },
    "/_opd/certificate": {
      "filePath": "_opd/certificate.tsx",
      "parent": "/_opd"
    },
    "/_opd/dayCare": {
      "filePath": "_opd/dayCare.tsx",
      "parent": "/_opd"
    },
    "/_opd/investigation-opd": {
      "filePath": "_opd/investigation-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/message-opd": {
      "filePath": "_opd/message-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/profil-opd": {
      "filePath": "_opd/profil-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/queue": {
      "filePath": "_opd/queue.tsx",
      "parent": "/_opd"
    },
    "/_opd/registration-opd": {
      "filePath": "_opd/registration-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/revisit": {
      "filePath": "_opd/revisit.tsx",
      "parent": "/_opd"
    },
    "/_opd/setting-opd": {
      "filePath": "_opd/setting-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/vaccin": {
      "filePath": "_opd/vaccin.tsx",
      "parent": "/_opd"
    },
    "/_radiology/radiology": {
      "filePath": "_radiology/radiology.tsx",
      "parent": "/_radiology"
    }
  }
}
ROUTE_MANIFEST_END */
