/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MenuPrincipalImport } from './routes/menu-principal'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/_home'
import { Route as IndexImport } from './routes/index'
import { Route as HomeStockStockImport } from './routes/_home/stock/stock'
import { Route as HomeRadiologyRadiologyImport } from './routes/_home/radiology/radiology'
import { Route as HomeNurseNurseImport } from './routes/_home/nurse/nurse'
import { Route as HomeLabLabImport } from './routes/_home/lab/lab'
import { Route as HomeDoctorDoctorImport } from './routes/_home/doctor/doctor'
import { Route as HomeAppointmentsAppointmentsImport } from './routes/_home/appointments/appointments'
import { Route as HomeAdminSettingImport } from './routes/_home/admin/setting'
import { Route as HomeAdminServiceImport } from './routes/_home/admin/service'
import { Route as HomeAdminReportImport } from './routes/_home/admin/report'
import { Route as HomeAdminProfilImport } from './routes/_home/admin/profil'
import { Route as HomeAdminPersonnelImport } from './routes/_home/admin/personnel'
import { Route as HomeAdminPatientImport } from './routes/_home/admin/patient'
import { Route as HomeAdminMessageImport } from './routes/_home/admin/message'
import { Route as HomeAdminDashboardImport } from './routes/_home/admin/dashboard'
import { Route as HomeOPDOpdImport } from './routes/_home/OPD/opd'
import { Route as HomeIPDIpdImport } from './routes/_home/IPD/ipd'

// Create/Update Routes

const MenuPrincipalRoute = MenuPrincipalImport.update({
  id: '/menu-principal',
  path: '/menu-principal',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeStockStockRoute = HomeStockStockImport.update({
  id: '/stock/stock',
  path: '/stock/stock',
  getParentRoute: () => HomeRoute,
} as any)

const HomeRadiologyRadiologyRoute = HomeRadiologyRadiologyImport.update({
  id: '/radiology/radiology',
  path: '/radiology/radiology',
  getParentRoute: () => HomeRoute,
} as any)

const HomeNurseNurseRoute = HomeNurseNurseImport.update({
  id: '/nurse/nurse',
  path: '/nurse/nurse',
  getParentRoute: () => HomeRoute,
} as any)

const HomeLabLabRoute = HomeLabLabImport.update({
  id: '/lab/lab',
  path: '/lab/lab',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDoctorDoctorRoute = HomeDoctorDoctorImport.update({
  id: '/doctor/doctor',
  path: '/doctor/doctor',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAppointmentsAppointmentsRoute =
  HomeAppointmentsAppointmentsImport.update({
    id: '/appointments/appointments',
    path: '/appointments/appointments',
    getParentRoute: () => HomeRoute,
  } as any)

const HomeAdminSettingRoute = HomeAdminSettingImport.update({
  id: '/admin/setting',
  path: '/admin/setting',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminServiceRoute = HomeAdminServiceImport.update({
  id: '/admin/service',
  path: '/admin/service',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminReportRoute = HomeAdminReportImport.update({
  id: '/admin/report',
  path: '/admin/report',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminProfilRoute = HomeAdminProfilImport.update({
  id: '/admin/profil',
  path: '/admin/profil',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminPersonnelRoute = HomeAdminPersonnelImport.update({
  id: '/admin/personnel',
  path: '/admin/personnel',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminPatientRoute = HomeAdminPatientImport.update({
  id: '/admin/patient',
  path: '/admin/patient',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminMessageRoute = HomeAdminMessageImport.update({
  id: '/admin/message',
  path: '/admin/message',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAdminDashboardRoute = HomeAdminDashboardImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => HomeRoute,
} as any)

const HomeOPDOpdRoute = HomeOPDOpdImport.update({
  id: '/OPD/opd',
  path: '/OPD/opd',
  getParentRoute: () => HomeRoute,
} as any)

const HomeIPDIpdRoute = HomeIPDIpdImport.update({
  id: '/IPD/ipd',
  path: '/IPD/ipd',
  getParentRoute: () => HomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/menu-principal': {
      id: '/menu-principal'
      path: '/menu-principal'
      fullPath: '/menu-principal'
      preLoaderRoute: typeof MenuPrincipalImport
      parentRoute: typeof rootRoute
    }
    '/_home/IPD/ipd': {
      id: '/_home/IPD/ipd'
      path: '/IPD/ipd'
      fullPath: '/IPD/ipd'
      preLoaderRoute: typeof HomeIPDIpdImport
      parentRoute: typeof HomeImport
    }
    '/_home/OPD/opd': {
      id: '/_home/OPD/opd'
      path: '/OPD/opd'
      fullPath: '/OPD/opd'
      preLoaderRoute: typeof HomeOPDOpdImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/dashboard': {
      id: '/_home/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof HomeAdminDashboardImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/message': {
      id: '/_home/admin/message'
      path: '/admin/message'
      fullPath: '/admin/message'
      preLoaderRoute: typeof HomeAdminMessageImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/patient': {
      id: '/_home/admin/patient'
      path: '/admin/patient'
      fullPath: '/admin/patient'
      preLoaderRoute: typeof HomeAdminPatientImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/personnel': {
      id: '/_home/admin/personnel'
      path: '/admin/personnel'
      fullPath: '/admin/personnel'
      preLoaderRoute: typeof HomeAdminPersonnelImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/profil': {
      id: '/_home/admin/profil'
      path: '/admin/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof HomeAdminProfilImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/report': {
      id: '/_home/admin/report'
      path: '/admin/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof HomeAdminReportImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/service': {
      id: '/_home/admin/service'
      path: '/admin/service'
      fullPath: '/admin/service'
      preLoaderRoute: typeof HomeAdminServiceImport
      parentRoute: typeof HomeImport
    }
    '/_home/admin/setting': {
      id: '/_home/admin/setting'
      path: '/admin/setting'
      fullPath: '/admin/setting'
      preLoaderRoute: typeof HomeAdminSettingImport
      parentRoute: typeof HomeImport
    }
    '/_home/appointments/appointments': {
      id: '/_home/appointments/appointments'
      path: '/appointments/appointments'
      fullPath: '/appointments/appointments'
      preLoaderRoute: typeof HomeAppointmentsAppointmentsImport
      parentRoute: typeof HomeImport
    }
    '/_home/doctor/doctor': {
      id: '/_home/doctor/doctor'
      path: '/doctor/doctor'
      fullPath: '/doctor/doctor'
      preLoaderRoute: typeof HomeDoctorDoctorImport
      parentRoute: typeof HomeImport
    }
    '/_home/lab/lab': {
      id: '/_home/lab/lab'
      path: '/lab/lab'
      fullPath: '/lab/lab'
      preLoaderRoute: typeof HomeLabLabImport
      parentRoute: typeof HomeImport
    }
    '/_home/nurse/nurse': {
      id: '/_home/nurse/nurse'
      path: '/nurse/nurse'
      fullPath: '/nurse/nurse'
      preLoaderRoute: typeof HomeNurseNurseImport
      parentRoute: typeof HomeImport
    }
    '/_home/radiology/radiology': {
      id: '/_home/radiology/radiology'
      path: '/radiology/radiology'
      fullPath: '/radiology/radiology'
      preLoaderRoute: typeof HomeRadiologyRadiologyImport
      parentRoute: typeof HomeImport
    }
    '/_home/stock/stock': {
      id: '/_home/stock/stock'
      path: '/stock/stock'
      fullPath: '/stock/stock'
      preLoaderRoute: typeof HomeStockStockImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

interface HomeRouteChildren {
  HomeIPDIpdRoute: typeof HomeIPDIpdRoute
  HomeOPDOpdRoute: typeof HomeOPDOpdRoute
  HomeAdminDashboardRoute: typeof HomeAdminDashboardRoute
  HomeAdminMessageRoute: typeof HomeAdminMessageRoute
  HomeAdminPatientRoute: typeof HomeAdminPatientRoute
  HomeAdminPersonnelRoute: typeof HomeAdminPersonnelRoute
  HomeAdminProfilRoute: typeof HomeAdminProfilRoute
  HomeAdminReportRoute: typeof HomeAdminReportRoute
  HomeAdminServiceRoute: typeof HomeAdminServiceRoute
  HomeAdminSettingRoute: typeof HomeAdminSettingRoute
  HomeAppointmentsAppointmentsRoute: typeof HomeAppointmentsAppointmentsRoute
  HomeDoctorDoctorRoute: typeof HomeDoctorDoctorRoute
  HomeLabLabRoute: typeof HomeLabLabRoute
  HomeNurseNurseRoute: typeof HomeNurseNurseRoute
  HomeRadiologyRadiologyRoute: typeof HomeRadiologyRadiologyRoute
  HomeStockStockRoute: typeof HomeStockStockRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIPDIpdRoute: HomeIPDIpdRoute,
  HomeOPDOpdRoute: HomeOPDOpdRoute,
  HomeAdminDashboardRoute: HomeAdminDashboardRoute,
  HomeAdminMessageRoute: HomeAdminMessageRoute,
  HomeAdminPatientRoute: HomeAdminPatientRoute,
  HomeAdminPersonnelRoute: HomeAdminPersonnelRoute,
  HomeAdminProfilRoute: HomeAdminProfilRoute,
  HomeAdminReportRoute: HomeAdminReportRoute,
  HomeAdminServiceRoute: HomeAdminServiceRoute,
  HomeAdminSettingRoute: HomeAdminSettingRoute,
  HomeAppointmentsAppointmentsRoute: HomeAppointmentsAppointmentsRoute,
  HomeDoctorDoctorRoute: HomeDoctorDoctorRoute,
  HomeLabLabRoute: HomeLabLabRoute,
  HomeNurseNurseRoute: HomeNurseNurseRoute,
  HomeRadiologyRadiologyRoute: HomeRadiologyRadiologyRoute,
  HomeStockStockRoute: HomeStockStockRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/IPD/ipd': typeof HomeIPDIpdRoute
  '/OPD/opd': typeof HomeOPDOpdRoute
  '/admin/dashboard': typeof HomeAdminDashboardRoute
  '/admin/message': typeof HomeAdminMessageRoute
  '/admin/patient': typeof HomeAdminPatientRoute
  '/admin/personnel': typeof HomeAdminPersonnelRoute
  '/admin/profil': typeof HomeAdminProfilRoute
  '/admin/report': typeof HomeAdminReportRoute
  '/admin/service': typeof HomeAdminServiceRoute
  '/admin/setting': typeof HomeAdminSettingRoute
  '/appointments/appointments': typeof HomeAppointmentsAppointmentsRoute
  '/doctor/doctor': typeof HomeDoctorDoctorRoute
  '/lab/lab': typeof HomeLabLabRoute
  '/nurse/nurse': typeof HomeNurseNurseRoute
  '/radiology/radiology': typeof HomeRadiologyRadiologyRoute
  '/stock/stock': typeof HomeStockStockRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/IPD/ipd': typeof HomeIPDIpdRoute
  '/OPD/opd': typeof HomeOPDOpdRoute
  '/admin/dashboard': typeof HomeAdminDashboardRoute
  '/admin/message': typeof HomeAdminMessageRoute
  '/admin/patient': typeof HomeAdminPatientRoute
  '/admin/personnel': typeof HomeAdminPersonnelRoute
  '/admin/profil': typeof HomeAdminProfilRoute
  '/admin/report': typeof HomeAdminReportRoute
  '/admin/service': typeof HomeAdminServiceRoute
  '/admin/setting': typeof HomeAdminSettingRoute
  '/appointments/appointments': typeof HomeAppointmentsAppointmentsRoute
  '/doctor/doctor': typeof HomeDoctorDoctorRoute
  '/lab/lab': typeof HomeLabLabRoute
  '/nurse/nurse': typeof HomeNurseNurseRoute
  '/radiology/radiology': typeof HomeRadiologyRadiologyRoute
  '/stock/stock': typeof HomeStockStockRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/_home/IPD/ipd': typeof HomeIPDIpdRoute
  '/_home/OPD/opd': typeof HomeOPDOpdRoute
  '/_home/admin/dashboard': typeof HomeAdminDashboardRoute
  '/_home/admin/message': typeof HomeAdminMessageRoute
  '/_home/admin/patient': typeof HomeAdminPatientRoute
  '/_home/admin/personnel': typeof HomeAdminPersonnelRoute
  '/_home/admin/profil': typeof HomeAdminProfilRoute
  '/_home/admin/report': typeof HomeAdminReportRoute
  '/_home/admin/service': typeof HomeAdminServiceRoute
  '/_home/admin/setting': typeof HomeAdminSettingRoute
  '/_home/appointments/appointments': typeof HomeAppointmentsAppointmentsRoute
  '/_home/doctor/doctor': typeof HomeDoctorDoctorRoute
  '/_home/lab/lab': typeof HomeLabLabRoute
  '/_home/nurse/nurse': typeof HomeNurseNurseRoute
  '/_home/radiology/radiology': typeof HomeRadiologyRadiologyRoute
  '/_home/stock/stock': typeof HomeStockStockRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/menu-principal'
    | '/IPD/ipd'
    | '/OPD/opd'
    | '/admin/dashboard'
    | '/admin/message'
    | '/admin/patient'
    | '/admin/personnel'
    | '/admin/profil'
    | '/admin/report'
    | '/admin/service'
    | '/admin/setting'
    | '/appointments/appointments'
    | '/doctor/doctor'
    | '/lab/lab'
    | '/nurse/nurse'
    | '/radiology/radiology'
    | '/stock/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/menu-principal'
    | '/IPD/ipd'
    | '/OPD/opd'
    | '/admin/dashboard'
    | '/admin/message'
    | '/admin/patient'
    | '/admin/personnel'
    | '/admin/profil'
    | '/admin/report'
    | '/admin/service'
    | '/admin/setting'
    | '/appointments/appointments'
    | '/doctor/doctor'
    | '/lab/lab'
    | '/nurse/nurse'
    | '/radiology/radiology'
    | '/stock/stock'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/login'
    | '/menu-principal'
    | '/_home/IPD/ipd'
    | '/_home/OPD/opd'
    | '/_home/admin/dashboard'
    | '/_home/admin/message'
    | '/_home/admin/patient'
    | '/_home/admin/personnel'
    | '/_home/admin/profil'
    | '/_home/admin/report'
    | '/_home/admin/service'
    | '/_home/admin/setting'
    | '/_home/appointments/appointments'
    | '/_home/doctor/doctor'
    | '/_home/lab/lab'
    | '/_home/nurse/nurse'
    | '/_home/radiology/radiology'
    | '/_home/stock/stock'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuPrincipalRoute: typeof MenuPrincipalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuPrincipalRoute: MenuPrincipalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_home",
        "/login",
        "/menu-principal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/IPD/ipd",
        "/_home/OPD/opd",
        "/_home/admin/dashboard",
        "/_home/admin/message",
        "/_home/admin/patient",
        "/_home/admin/personnel",
        "/_home/admin/profil",
        "/_home/admin/report",
        "/_home/admin/service",
        "/_home/admin/setting",
        "/_home/appointments/appointments",
        "/_home/doctor/doctor",
        "/_home/lab/lab",
        "/_home/nurse/nurse",
        "/_home/radiology/radiology",
        "/_home/stock/stock"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/menu-principal": {
      "filePath": "menu-principal.tsx"
    },
    "/_home/IPD/ipd": {
      "filePath": "_home/IPD/ipd.tsx",
      "parent": "/_home"
    },
    "/_home/OPD/opd": {
      "filePath": "_home/OPD/opd.tsx",
      "parent": "/_home"
    },
    "/_home/admin/dashboard": {
      "filePath": "_home/admin/dashboard.tsx",
      "parent": "/_home"
    },
    "/_home/admin/message": {
      "filePath": "_home/admin/message.tsx",
      "parent": "/_home"
    },
    "/_home/admin/patient": {
      "filePath": "_home/admin/patient.tsx",
      "parent": "/_home"
    },
    "/_home/admin/personnel": {
      "filePath": "_home/admin/personnel.tsx",
      "parent": "/_home"
    },
    "/_home/admin/profil": {
      "filePath": "_home/admin/profil.tsx",
      "parent": "/_home"
    },
    "/_home/admin/report": {
      "filePath": "_home/admin/report.tsx",
      "parent": "/_home"
    },
    "/_home/admin/service": {
      "filePath": "_home/admin/service.tsx",
      "parent": "/_home"
    },
    "/_home/admin/setting": {
      "filePath": "_home/admin/setting.tsx",
      "parent": "/_home"
    },
    "/_home/appointments/appointments": {
      "filePath": "_home/appointments/appointments.tsx",
      "parent": "/_home"
    },
    "/_home/doctor/doctor": {
      "filePath": "_home/doctor/doctor.tsx",
      "parent": "/_home"
    },
    "/_home/lab/lab": {
      "filePath": "_home/lab/lab.tsx",
      "parent": "/_home"
    },
    "/_home/nurse/nurse": {
      "filePath": "_home/nurse/nurse.tsx",
      "parent": "/_home"
    },
    "/_home/radiology/radiology": {
      "filePath": "_home/radiology/radiology.tsx",
      "parent": "/_home"
    },
    "/_home/stock/stock": {
      "filePath": "_home/stock/stock.tsx",
      "parent": "/_home"
    }
  }
}
ROUTE_MANIFEST_END */
