/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MenuPrincipalImport } from './routes/menu-principal'
import { Route as LoginImport } from './routes/login'
import { Route as RadiologyImport } from './routes/_radiology'
import { Route as OpdImport } from './routes/_opd'
import { Route as NurseImport } from './routes/_nurse'
import { Route as MedicalStockImport } from './routes/_medical-stock'
import { Route as LabImport } from './routes/_lab'
import { Route as IpdImport } from './routes/_ipd'
import { Route as HomeImport } from './routes/_home'
import { Route as DoctorImport } from './routes/_doctor'
import { Route as AppointmentsImport } from './routes/_appointments'
import { Route as IndexImport } from './routes/index'
import { Route as RadiologyRadiologyImport } from './routes/_radiology/radiology'
import { Route as OpdVaccinImport } from './routes/_opd/vaccin'
import { Route as OpdSettingOpdImport } from './routes/_opd/setting-opd'
import { Route as OpdRevisitImport } from './routes/_opd/revisit'
import { Route as OpdRegistrationOpdImport } from './routes/_opd/registration-opd'
import { Route as OpdQueueImport } from './routes/_opd/queue'
import { Route as OpdProfilOpdImport } from './routes/_opd/profil-opd'
import { Route as OpdMessageOpdImport } from './routes/_opd/message-opd'
import { Route as OpdInvestigationOpdImport } from './routes/_opd/investigation-opd'
import { Route as OpdDayCareImport } from './routes/_opd/dayCare'
import { Route as OpdCertificateImport } from './routes/_opd/certificate'
import { Route as OpdBirthRegistrationImport } from './routes/_opd/birth-registration'
import { Route as NurseSettingNurseImport } from './routes/_nurse/setting-nurse'
import { Route as NurseReportNurseImport } from './routes/_nurse/report-nurse'
import { Route as NursePatientMedecineImport } from './routes/_nurse/patient-medecine'
import { Route as NurseFichePatientImport } from './routes/_nurse/fiche-patient'
import { Route as NurseDashboardNurseImport } from './routes/_nurse/dashboard-nurse'
import { Route as NurseChecklistImport } from './routes/_nurse/checklist'
import { Route as MedicalStockSettingStockImport } from './routes/_medical-stock/setting-stock'
import { Route as MedicalStockProfilStockImport } from './routes/_medical-stock/profil-stock'
import { Route as MedicalStockMessageStockImport } from './routes/_medical-stock/message-stock'
import { Route as MedicalStockMaintenanceImport } from './routes/_medical-stock/maintenance'
import { Route as MedicalStockInventaireImport } from './routes/_medical-stock/inventaire'
import { Route as MedicalStockDashboardStockImport } from './routes/_medical-stock/dashboard-stock'
import { Route as MedicalStockCommandeImport } from './routes/_medical-stock/commande'
import { Route as MedicalStockArticleImport } from './routes/_medical-stock/article'
import { Route as MedicalStockApprovisionnementImport } from './routes/_medical-stock/approvisionnement'
import { Route as MedicalStockAdministrationImport } from './routes/_medical-stock/administration'
import { Route as LabSettingLabImport } from './routes/_lab/setting-lab'
import { Route as LabReportLabImport } from './routes/_lab/report-lab'
import { Route as LabOpdRequestImport } from './routes/_lab/opd-request'
import { Route as LabIpdRequestImport } from './routes/_lab/ipd-request'
import { Route as IpdReportIpdImport } from './routes/_ipd/report-ipd'
import { Route as IpdRegistrationIpdImport } from './routes/_ipd/registration-ipd'
import { Route as IpdPaymentImport } from './routes/_ipd/payment'
import { Route as IpdOTImport } from './routes/_ipd/oT'
import { Route as IpdMedecinesImport } from './routes/_ipd/medecines'
import { Route as IpdIpdImport } from './routes/_ipd/ipd'
import { Route as IpdInvestigationImport } from './routes/_ipd/investigation'
import { Route as IpdDischargeImport } from './routes/_ipd/discharge'
import { Route as HomeSettingImport } from './routes/_home/setting'
import { Route as HomeServiceImport } from './routes/_home/service'
import { Route as HomeReportImport } from './routes/_home/report'
import { Route as HomeProfilImport } from './routes/_home/profil'
import { Route as HomePersonnelImport } from './routes/_home/personnel'
import { Route as HomePatientImport } from './routes/_home/patient'
import { Route as HomeMessageImport } from './routes/_home/message'
import { Route as HomeDashboardImport } from './routes/_home/dashboard'
import { Route as DoctorSettingDoctorImport } from './routes/_doctor/setting-doctor'
import { Route as DoctorProfilDoctorImport } from './routes/_doctor/profil-doctor'
import { Route as DoctorPatientDoctorImport } from './routes/_doctor/patient-doctor'
import { Route as DoctorOrdonnanceImport } from './routes/_doctor/ordonnance'
import { Route as DoctorMessageDoctorImport } from './routes/_doctor/message-doctor'
import { Route as DoctorDashboardDoctorImport } from './routes/_doctor/dashboard-doctor'
import { Route as DoctorAppointmentDoctorImport } from './routes/_doctor/appointment-doctor'
import { Route as AppointmentsSuiviAppointmentImport } from './routes/_appointments/suiviAppointment'
import { Route as AppointmentsSettingAppointmentImport } from './routes/_appointments/setting-appointment'
import { Route as AppointmentsProfilAppointmentImport } from './routes/_appointments/profil-appointment'
import { Route as AppointmentsPriseAppointmentImport } from './routes/_appointments/priseAppointment'
import { Route as AppointmentsMessageAppointmentImport } from './routes/_appointments/message-appointment'
import { Route as AppointmentsDashboardAppointmentImport } from './routes/_appointments/dashboard-appointment'

// Create/Update Routes

const MenuPrincipalRoute = MenuPrincipalImport.update({
  id: '/menu-principal',
  path: '/menu-principal',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const RadiologyRoute = RadiologyImport.update({
  id: '/_radiology',
  getParentRoute: () => rootRoute,
} as any)

const OpdRoute = OpdImport.update({
  id: '/_opd',
  getParentRoute: () => rootRoute,
} as any)

const NurseRoute = NurseImport.update({
  id: '/_nurse',
  getParentRoute: () => rootRoute,
} as any)

const MedicalStockRoute = MedicalStockImport.update({
  id: '/_medical-stock',
  getParentRoute: () => rootRoute,
} as any)

const LabRoute = LabImport.update({
  id: '/_lab',
  getParentRoute: () => rootRoute,
} as any)

const IpdRoute = IpdImport.update({
  id: '/_ipd',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const DoctorRoute = DoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentsRoute = AppointmentsImport.update({
  id: '/_appointments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RadiologyRadiologyRoute = RadiologyRadiologyImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => RadiologyRoute,
} as any)

const OpdVaccinRoute = OpdVaccinImport.update({
  id: '/vaccin',
  path: '/vaccin',
  getParentRoute: () => OpdRoute,
} as any)

const OpdSettingOpdRoute = OpdSettingOpdImport.update({
  id: '/setting-opd',
  path: '/setting-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdRevisitRoute = OpdRevisitImport.update({
  id: '/revisit',
  path: '/revisit',
  getParentRoute: () => OpdRoute,
} as any)

const OpdRegistrationOpdRoute = OpdRegistrationOpdImport.update({
  id: '/registration-opd',
  path: '/registration-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdQueueRoute = OpdQueueImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OpdRoute,
} as any)

const OpdProfilOpdRoute = OpdProfilOpdImport.update({
  id: '/profil-opd',
  path: '/profil-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdMessageOpdRoute = OpdMessageOpdImport.update({
  id: '/message-opd',
  path: '/message-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdInvestigationOpdRoute = OpdInvestigationOpdImport.update({
  id: '/investigation-opd',
  path: '/investigation-opd',
  getParentRoute: () => OpdRoute,
} as any)

const OpdDayCareRoute = OpdDayCareImport.update({
  id: '/dayCare',
  path: '/dayCare',
  getParentRoute: () => OpdRoute,
} as any)

const OpdCertificateRoute = OpdCertificateImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => OpdRoute,
} as any)

const OpdBirthRegistrationRoute = OpdBirthRegistrationImport.update({
  id: '/birth-registration',
  path: '/birth-registration',
  getParentRoute: () => OpdRoute,
} as any)

const NurseSettingNurseRoute = NurseSettingNurseImport.update({
  id: '/setting-nurse',
  path: '/setting-nurse',
  getParentRoute: () => NurseRoute,
} as any)

const NurseReportNurseRoute = NurseReportNurseImport.update({
  id: '/report-nurse',
  path: '/report-nurse',
  getParentRoute: () => NurseRoute,
} as any)

const NursePatientMedecineRoute = NursePatientMedecineImport.update({
  id: '/patient-medecine',
  path: '/patient-medecine',
  getParentRoute: () => NurseRoute,
} as any)

const NurseFichePatientRoute = NurseFichePatientImport.update({
  id: '/fiche-patient',
  path: '/fiche-patient',
  getParentRoute: () => NurseRoute,
} as any)

const NurseDashboardNurseRoute = NurseDashboardNurseImport.update({
  id: '/dashboard-nurse',
  path: '/dashboard-nurse',
  getParentRoute: () => NurseRoute,
} as any)

const NurseChecklistRoute = NurseChecklistImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => NurseRoute,
} as any)

const MedicalStockSettingStockRoute = MedicalStockSettingStockImport.update({
  id: '/setting-stock',
  path: '/setting-stock',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockProfilStockRoute = MedicalStockProfilStockImport.update({
  id: '/profil-stock',
  path: '/profil-stock',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockMessageStockRoute = MedicalStockMessageStockImport.update({
  id: '/message-stock',
  path: '/message-stock',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockMaintenanceRoute = MedicalStockMaintenanceImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockInventaireRoute = MedicalStockInventaireImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockDashboardStockRoute = MedicalStockDashboardStockImport.update(
  {
    id: '/dashboard-stock',
    path: '/dashboard-stock',
    getParentRoute: () => MedicalStockRoute,
  } as any,
)

const MedicalStockCommandeRoute = MedicalStockCommandeImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockArticleRoute = MedicalStockArticleImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => MedicalStockRoute,
} as any)

const MedicalStockApprovisionnementRoute =
  MedicalStockApprovisionnementImport.update({
    id: '/approvisionnement',
    path: '/approvisionnement',
    getParentRoute: () => MedicalStockRoute,
  } as any)

const MedicalStockAdministrationRoute = MedicalStockAdministrationImport.update(
  {
    id: '/administration',
    path: '/administration',
    getParentRoute: () => MedicalStockRoute,
  } as any,
)

const LabSettingLabRoute = LabSettingLabImport.update({
  id: '/setting-lab',
  path: '/setting-lab',
  getParentRoute: () => LabRoute,
} as any)

const LabReportLabRoute = LabReportLabImport.update({
  id: '/report-lab',
  path: '/report-lab',
  getParentRoute: () => LabRoute,
} as any)

const LabOpdRequestRoute = LabOpdRequestImport.update({
  id: '/opd-request',
  path: '/opd-request',
  getParentRoute: () => LabRoute,
} as any)

const LabIpdRequestRoute = LabIpdRequestImport.update({
  id: '/ipd-request',
  path: '/ipd-request',
  getParentRoute: () => LabRoute,
} as any)

const IpdReportIpdRoute = IpdReportIpdImport.update({
  id: '/report-ipd',
  path: '/report-ipd',
  getParentRoute: () => IpdRoute,
} as any)

const IpdRegistrationIpdRoute = IpdRegistrationIpdImport.update({
  id: '/registration-ipd',
  path: '/registration-ipd',
  getParentRoute: () => IpdRoute,
} as any)

const IpdPaymentRoute = IpdPaymentImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => IpdRoute,
} as any)

const IpdOTRoute = IpdOTImport.update({
  id: '/oT',
  path: '/oT',
  getParentRoute: () => IpdRoute,
} as any)

const IpdMedecinesRoute = IpdMedecinesImport.update({
  id: '/medecines',
  path: '/medecines',
  getParentRoute: () => IpdRoute,
} as any)

const IpdIpdRoute = IpdIpdImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => IpdRoute,
} as any)

const IpdInvestigationRoute = IpdInvestigationImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => IpdRoute,
} as any)

const IpdDischargeRoute = IpdDischargeImport.update({
  id: '/discharge',
  path: '/discharge',
  getParentRoute: () => IpdRoute,
} as any)

const HomeSettingRoute = HomeSettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => HomeRoute,
} as any)

const HomeServiceRoute = HomeServiceImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => HomeRoute,
} as any)

const HomeReportRoute = HomeReportImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => HomeRoute,
} as any)

const HomeProfilRoute = HomeProfilImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => HomeRoute,
} as any)

const HomePersonnelRoute = HomePersonnelImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => HomeRoute,
} as any)

const HomePatientRoute = HomePatientImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => HomeRoute,
} as any)

const HomeMessageRoute = HomeMessageImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDashboardRoute = HomeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRoute,
} as any)

const DoctorSettingDoctorRoute = DoctorSettingDoctorImport.update({
  id: '/setting-doctor',
  path: '/setting-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorProfilDoctorRoute = DoctorProfilDoctorImport.update({
  id: '/profil-doctor',
  path: '/profil-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorPatientDoctorRoute = DoctorPatientDoctorImport.update({
  id: '/patient-doctor',
  path: '/patient-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorOrdonnanceRoute = DoctorOrdonnanceImport.update({
  id: '/ordonnance',
  path: '/ordonnance',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorMessageDoctorRoute = DoctorMessageDoctorImport.update({
  id: '/message-doctor',
  path: '/message-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorDashboardDoctorRoute = DoctorDashboardDoctorImport.update({
  id: '/dashboard-doctor',
  path: '/dashboard-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const DoctorAppointmentDoctorRoute = DoctorAppointmentDoctorImport.update({
  id: '/appointment-doctor',
  path: '/appointment-doctor',
  getParentRoute: () => DoctorRoute,
} as any)

const AppointmentsSuiviAppointmentRoute =
  AppointmentsSuiviAppointmentImport.update({
    id: '/suiviAppointment',
    path: '/suiviAppointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsSettingAppointmentRoute =
  AppointmentsSettingAppointmentImport.update({
    id: '/setting-appointment',
    path: '/setting-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsProfilAppointmentRoute =
  AppointmentsProfilAppointmentImport.update({
    id: '/profil-appointment',
    path: '/profil-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsPriseAppointmentRoute =
  AppointmentsPriseAppointmentImport.update({
    id: '/priseAppointment',
    path: '/priseAppointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsMessageAppointmentRoute =
  AppointmentsMessageAppointmentImport.update({
    id: '/message-appointment',
    path: '/message-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

const AppointmentsDashboardAppointmentRoute =
  AppointmentsDashboardAppointmentImport.update({
    id: '/dashboard-appointment',
    path: '/dashboard-appointment',
    getParentRoute: () => AppointmentsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_appointments': {
      id: '/_appointments'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppointmentsImport
      parentRoute: typeof rootRoute
    }
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DoctorImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_ipd': {
      id: '/_ipd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IpdImport
      parentRoute: typeof rootRoute
    }
    '/_lab': {
      id: '/_lab'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LabImport
      parentRoute: typeof rootRoute
    }
    '/_medical-stock': {
      id: '/_medical-stock'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MedicalStockImport
      parentRoute: typeof rootRoute
    }
    '/_nurse': {
      id: '/_nurse'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NurseImport
      parentRoute: typeof rootRoute
    }
    '/_opd': {
      id: '/_opd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OpdImport
      parentRoute: typeof rootRoute
    }
    '/_radiology': {
      id: '/_radiology'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RadiologyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/menu-principal': {
      id: '/menu-principal'
      path: '/menu-principal'
      fullPath: '/menu-principal'
      preLoaderRoute: typeof MenuPrincipalImport
      parentRoute: typeof rootRoute
    }
    '/_appointments/dashboard-appointment': {
      id: '/_appointments/dashboard-appointment'
      path: '/dashboard-appointment'
      fullPath: '/dashboard-appointment'
      preLoaderRoute: typeof AppointmentsDashboardAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/message-appointment': {
      id: '/_appointments/message-appointment'
      path: '/message-appointment'
      fullPath: '/message-appointment'
      preLoaderRoute: typeof AppointmentsMessageAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/priseAppointment': {
      id: '/_appointments/priseAppointment'
      path: '/priseAppointment'
      fullPath: '/priseAppointment'
      preLoaderRoute: typeof AppointmentsPriseAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/profil-appointment': {
      id: '/_appointments/profil-appointment'
      path: '/profil-appointment'
      fullPath: '/profil-appointment'
      preLoaderRoute: typeof AppointmentsProfilAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/setting-appointment': {
      id: '/_appointments/setting-appointment'
      path: '/setting-appointment'
      fullPath: '/setting-appointment'
      preLoaderRoute: typeof AppointmentsSettingAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_appointments/suiviAppointment': {
      id: '/_appointments/suiviAppointment'
      path: '/suiviAppointment'
      fullPath: '/suiviAppointment'
      preLoaderRoute: typeof AppointmentsSuiviAppointmentImport
      parentRoute: typeof AppointmentsImport
    }
    '/_doctor/appointment-doctor': {
      id: '/_doctor/appointment-doctor'
      path: '/appointment-doctor'
      fullPath: '/appointment-doctor'
      preLoaderRoute: typeof DoctorAppointmentDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/dashboard-doctor': {
      id: '/_doctor/dashboard-doctor'
      path: '/dashboard-doctor'
      fullPath: '/dashboard-doctor'
      preLoaderRoute: typeof DoctorDashboardDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/message-doctor': {
      id: '/_doctor/message-doctor'
      path: '/message-doctor'
      fullPath: '/message-doctor'
      preLoaderRoute: typeof DoctorMessageDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/ordonnance': {
      id: '/_doctor/ordonnance'
      path: '/ordonnance'
      fullPath: '/ordonnance'
      preLoaderRoute: typeof DoctorOrdonnanceImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/patient-doctor': {
      id: '/_doctor/patient-doctor'
      path: '/patient-doctor'
      fullPath: '/patient-doctor'
      preLoaderRoute: typeof DoctorPatientDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/profil-doctor': {
      id: '/_doctor/profil-doctor'
      path: '/profil-doctor'
      fullPath: '/profil-doctor'
      preLoaderRoute: typeof DoctorProfilDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_doctor/setting-doctor': {
      id: '/_doctor/setting-doctor'
      path: '/setting-doctor'
      fullPath: '/setting-doctor'
      preLoaderRoute: typeof DoctorSettingDoctorImport
      parentRoute: typeof DoctorImport
    }
    '/_home/dashboard': {
      id: '/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HomeDashboardImport
      parentRoute: typeof HomeImport
    }
    '/_home/message': {
      id: '/_home/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof HomeMessageImport
      parentRoute: typeof HomeImport
    }
    '/_home/patient': {
      id: '/_home/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof HomePatientImport
      parentRoute: typeof HomeImport
    }
    '/_home/personnel': {
      id: '/_home/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof HomePersonnelImport
      parentRoute: typeof HomeImport
    }
    '/_home/profil': {
      id: '/_home/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof HomeProfilImport
      parentRoute: typeof HomeImport
    }
    '/_home/report': {
      id: '/_home/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof HomeReportImport
      parentRoute: typeof HomeImport
    }
    '/_home/service': {
      id: '/_home/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof HomeServiceImport
      parentRoute: typeof HomeImport
    }
    '/_home/setting': {
      id: '/_home/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof HomeSettingImport
      parentRoute: typeof HomeImport
    }
    '/_ipd/discharge': {
      id: '/_ipd/discharge'
      path: '/discharge'
      fullPath: '/discharge'
      preLoaderRoute: typeof IpdDischargeImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/investigation': {
      id: '/_ipd/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof IpdInvestigationImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/ipd': {
      id: '/_ipd/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof IpdIpdImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/medecines': {
      id: '/_ipd/medecines'
      path: '/medecines'
      fullPath: '/medecines'
      preLoaderRoute: typeof IpdMedecinesImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/oT': {
      id: '/_ipd/oT'
      path: '/oT'
      fullPath: '/oT'
      preLoaderRoute: typeof IpdOTImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/payment': {
      id: '/_ipd/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof IpdPaymentImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/registration-ipd': {
      id: '/_ipd/registration-ipd'
      path: '/registration-ipd'
      fullPath: '/registration-ipd'
      preLoaderRoute: typeof IpdRegistrationIpdImport
      parentRoute: typeof IpdImport
    }
    '/_ipd/report-ipd': {
      id: '/_ipd/report-ipd'
      path: '/report-ipd'
      fullPath: '/report-ipd'
      preLoaderRoute: typeof IpdReportIpdImport
      parentRoute: typeof IpdImport
    }
    '/_lab/ipd-request': {
      id: '/_lab/ipd-request'
      path: '/ipd-request'
      fullPath: '/ipd-request'
      preLoaderRoute: typeof LabIpdRequestImport
      parentRoute: typeof LabImport
    }
    '/_lab/opd-request': {
      id: '/_lab/opd-request'
      path: '/opd-request'
      fullPath: '/opd-request'
      preLoaderRoute: typeof LabOpdRequestImport
      parentRoute: typeof LabImport
    }
    '/_lab/report-lab': {
      id: '/_lab/report-lab'
      path: '/report-lab'
      fullPath: '/report-lab'
      preLoaderRoute: typeof LabReportLabImport
      parentRoute: typeof LabImport
    }
    '/_lab/setting-lab': {
      id: '/_lab/setting-lab'
      path: '/setting-lab'
      fullPath: '/setting-lab'
      preLoaderRoute: typeof LabSettingLabImport
      parentRoute: typeof LabImport
    }
    '/_medical-stock/administration': {
      id: '/_medical-stock/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof MedicalStockAdministrationImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/approvisionnement': {
      id: '/_medical-stock/approvisionnement'
      path: '/approvisionnement'
      fullPath: '/approvisionnement'
      preLoaderRoute: typeof MedicalStockApprovisionnementImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/article': {
      id: '/_medical-stock/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof MedicalStockArticleImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/commande': {
      id: '/_medical-stock/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof MedicalStockCommandeImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/dashboard-stock': {
      id: '/_medical-stock/dashboard-stock'
      path: '/dashboard-stock'
      fullPath: '/dashboard-stock'
      preLoaderRoute: typeof MedicalStockDashboardStockImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/inventaire': {
      id: '/_medical-stock/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof MedicalStockInventaireImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/maintenance': {
      id: '/_medical-stock/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MedicalStockMaintenanceImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/message-stock': {
      id: '/_medical-stock/message-stock'
      path: '/message-stock'
      fullPath: '/message-stock'
      preLoaderRoute: typeof MedicalStockMessageStockImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/profil-stock': {
      id: '/_medical-stock/profil-stock'
      path: '/profil-stock'
      fullPath: '/profil-stock'
      preLoaderRoute: typeof MedicalStockProfilStockImport
      parentRoute: typeof MedicalStockImport
    }
    '/_medical-stock/setting-stock': {
      id: '/_medical-stock/setting-stock'
      path: '/setting-stock'
      fullPath: '/setting-stock'
      preLoaderRoute: typeof MedicalStockSettingStockImport
      parentRoute: typeof MedicalStockImport
    }
    '/_nurse/checklist': {
      id: '/_nurse/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof NurseChecklistImport
      parentRoute: typeof NurseImport
    }
    '/_nurse/dashboard-nurse': {
      id: '/_nurse/dashboard-nurse'
      path: '/dashboard-nurse'
      fullPath: '/dashboard-nurse'
      preLoaderRoute: typeof NurseDashboardNurseImport
      parentRoute: typeof NurseImport
    }
    '/_nurse/fiche-patient': {
      id: '/_nurse/fiche-patient'
      path: '/fiche-patient'
      fullPath: '/fiche-patient'
      preLoaderRoute: typeof NurseFichePatientImport
      parentRoute: typeof NurseImport
    }
    '/_nurse/patient-medecine': {
      id: '/_nurse/patient-medecine'
      path: '/patient-medecine'
      fullPath: '/patient-medecine'
      preLoaderRoute: typeof NursePatientMedecineImport
      parentRoute: typeof NurseImport
    }
    '/_nurse/report-nurse': {
      id: '/_nurse/report-nurse'
      path: '/report-nurse'
      fullPath: '/report-nurse'
      preLoaderRoute: typeof NurseReportNurseImport
      parentRoute: typeof NurseImport
    }
    '/_nurse/setting-nurse': {
      id: '/_nurse/setting-nurse'
      path: '/setting-nurse'
      fullPath: '/setting-nurse'
      preLoaderRoute: typeof NurseSettingNurseImport
      parentRoute: typeof NurseImport
    }
    '/_opd/birth-registration': {
      id: '/_opd/birth-registration'
      path: '/birth-registration'
      fullPath: '/birth-registration'
      preLoaderRoute: typeof OpdBirthRegistrationImport
      parentRoute: typeof OpdImport
    }
    '/_opd/certificate': {
      id: '/_opd/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof OpdCertificateImport
      parentRoute: typeof OpdImport
    }
    '/_opd/dayCare': {
      id: '/_opd/dayCare'
      path: '/dayCare'
      fullPath: '/dayCare'
      preLoaderRoute: typeof OpdDayCareImport
      parentRoute: typeof OpdImport
    }
    '/_opd/investigation-opd': {
      id: '/_opd/investigation-opd'
      path: '/investigation-opd'
      fullPath: '/investigation-opd'
      preLoaderRoute: typeof OpdInvestigationOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/message-opd': {
      id: '/_opd/message-opd'
      path: '/message-opd'
      fullPath: '/message-opd'
      preLoaderRoute: typeof OpdMessageOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/profil-opd': {
      id: '/_opd/profil-opd'
      path: '/profil-opd'
      fullPath: '/profil-opd'
      preLoaderRoute: typeof OpdProfilOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/queue': {
      id: '/_opd/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof OpdQueueImport
      parentRoute: typeof OpdImport
    }
    '/_opd/registration-opd': {
      id: '/_opd/registration-opd'
      path: '/registration-opd'
      fullPath: '/registration-opd'
      preLoaderRoute: typeof OpdRegistrationOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/revisit': {
      id: '/_opd/revisit'
      path: '/revisit'
      fullPath: '/revisit'
      preLoaderRoute: typeof OpdRevisitImport
      parentRoute: typeof OpdImport
    }
    '/_opd/setting-opd': {
      id: '/_opd/setting-opd'
      path: '/setting-opd'
      fullPath: '/setting-opd'
      preLoaderRoute: typeof OpdSettingOpdImport
      parentRoute: typeof OpdImport
    }
    '/_opd/vaccin': {
      id: '/_opd/vaccin'
      path: '/vaccin'
      fullPath: '/vaccin'
      preLoaderRoute: typeof OpdVaccinImport
      parentRoute: typeof OpdImport
    }
    '/_radiology/radiology': {
      id: '/_radiology/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRadiologyImport
      parentRoute: typeof RadiologyImport
    }
  }
}

// Create and export the route tree

interface AppointmentsRouteChildren {
  AppointmentsDashboardAppointmentRoute: typeof AppointmentsDashboardAppointmentRoute
  AppointmentsMessageAppointmentRoute: typeof AppointmentsMessageAppointmentRoute
  AppointmentsPriseAppointmentRoute: typeof AppointmentsPriseAppointmentRoute
  AppointmentsProfilAppointmentRoute: typeof AppointmentsProfilAppointmentRoute
  AppointmentsSettingAppointmentRoute: typeof AppointmentsSettingAppointmentRoute
  AppointmentsSuiviAppointmentRoute: typeof AppointmentsSuiviAppointmentRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsDashboardAppointmentRoute: AppointmentsDashboardAppointmentRoute,
  AppointmentsMessageAppointmentRoute: AppointmentsMessageAppointmentRoute,
  AppointmentsPriseAppointmentRoute: AppointmentsPriseAppointmentRoute,
  AppointmentsProfilAppointmentRoute: AppointmentsProfilAppointmentRoute,
  AppointmentsSettingAppointmentRoute: AppointmentsSettingAppointmentRoute,
  AppointmentsSuiviAppointmentRoute: AppointmentsSuiviAppointmentRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAppointmentDoctorRoute: typeof DoctorAppointmentDoctorRoute
  DoctorDashboardDoctorRoute: typeof DoctorDashboardDoctorRoute
  DoctorMessageDoctorRoute: typeof DoctorMessageDoctorRoute
  DoctorOrdonnanceRoute: typeof DoctorOrdonnanceRoute
  DoctorPatientDoctorRoute: typeof DoctorPatientDoctorRoute
  DoctorProfilDoctorRoute: typeof DoctorProfilDoctorRoute
  DoctorSettingDoctorRoute: typeof DoctorSettingDoctorRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentDoctorRoute: DoctorAppointmentDoctorRoute,
  DoctorDashboardDoctorRoute: DoctorDashboardDoctorRoute,
  DoctorMessageDoctorRoute: DoctorMessageDoctorRoute,
  DoctorOrdonnanceRoute: DoctorOrdonnanceRoute,
  DoctorPatientDoctorRoute: DoctorPatientDoctorRoute,
  DoctorProfilDoctorRoute: DoctorProfilDoctorRoute,
  DoctorSettingDoctorRoute: DoctorSettingDoctorRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface HomeRouteChildren {
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeMessageRoute: typeof HomeMessageRoute
  HomePatientRoute: typeof HomePatientRoute
  HomePersonnelRoute: typeof HomePersonnelRoute
  HomeProfilRoute: typeof HomeProfilRoute
  HomeReportRoute: typeof HomeReportRoute
  HomeServiceRoute: typeof HomeServiceRoute
  HomeSettingRoute: typeof HomeSettingRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeDashboardRoute: HomeDashboardRoute,
  HomeMessageRoute: HomeMessageRoute,
  HomePatientRoute: HomePatientRoute,
  HomePersonnelRoute: HomePersonnelRoute,
  HomeProfilRoute: HomeProfilRoute,
  HomeReportRoute: HomeReportRoute,
  HomeServiceRoute: HomeServiceRoute,
  HomeSettingRoute: HomeSettingRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface IpdRouteChildren {
  IpdDischargeRoute: typeof IpdDischargeRoute
  IpdInvestigationRoute: typeof IpdInvestigationRoute
  IpdIpdRoute: typeof IpdIpdRoute
  IpdMedecinesRoute: typeof IpdMedecinesRoute
  IpdOTRoute: typeof IpdOTRoute
  IpdPaymentRoute: typeof IpdPaymentRoute
  IpdRegistrationIpdRoute: typeof IpdRegistrationIpdRoute
  IpdReportIpdRoute: typeof IpdReportIpdRoute
}

const IpdRouteChildren: IpdRouteChildren = {
  IpdDischargeRoute: IpdDischargeRoute,
  IpdInvestigationRoute: IpdInvestigationRoute,
  IpdIpdRoute: IpdIpdRoute,
  IpdMedecinesRoute: IpdMedecinesRoute,
  IpdOTRoute: IpdOTRoute,
  IpdPaymentRoute: IpdPaymentRoute,
  IpdRegistrationIpdRoute: IpdRegistrationIpdRoute,
  IpdReportIpdRoute: IpdReportIpdRoute,
}

const IpdRouteWithChildren = IpdRoute._addFileChildren(IpdRouteChildren)

interface LabRouteChildren {
  LabIpdRequestRoute: typeof LabIpdRequestRoute
  LabOpdRequestRoute: typeof LabOpdRequestRoute
  LabReportLabRoute: typeof LabReportLabRoute
  LabSettingLabRoute: typeof LabSettingLabRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabIpdRequestRoute: LabIpdRequestRoute,
  LabOpdRequestRoute: LabOpdRequestRoute,
  LabReportLabRoute: LabReportLabRoute,
  LabSettingLabRoute: LabSettingLabRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface MedicalStockRouteChildren {
  MedicalStockAdministrationRoute: typeof MedicalStockAdministrationRoute
  MedicalStockApprovisionnementRoute: typeof MedicalStockApprovisionnementRoute
  MedicalStockArticleRoute: typeof MedicalStockArticleRoute
  MedicalStockCommandeRoute: typeof MedicalStockCommandeRoute
  MedicalStockDashboardStockRoute: typeof MedicalStockDashboardStockRoute
  MedicalStockInventaireRoute: typeof MedicalStockInventaireRoute
  MedicalStockMaintenanceRoute: typeof MedicalStockMaintenanceRoute
  MedicalStockMessageStockRoute: typeof MedicalStockMessageStockRoute
  MedicalStockProfilStockRoute: typeof MedicalStockProfilStockRoute
  MedicalStockSettingStockRoute: typeof MedicalStockSettingStockRoute
}

const MedicalStockRouteChildren: MedicalStockRouteChildren = {
  MedicalStockAdministrationRoute: MedicalStockAdministrationRoute,
  MedicalStockApprovisionnementRoute: MedicalStockApprovisionnementRoute,
  MedicalStockArticleRoute: MedicalStockArticleRoute,
  MedicalStockCommandeRoute: MedicalStockCommandeRoute,
  MedicalStockDashboardStockRoute: MedicalStockDashboardStockRoute,
  MedicalStockInventaireRoute: MedicalStockInventaireRoute,
  MedicalStockMaintenanceRoute: MedicalStockMaintenanceRoute,
  MedicalStockMessageStockRoute: MedicalStockMessageStockRoute,
  MedicalStockProfilStockRoute: MedicalStockProfilStockRoute,
  MedicalStockSettingStockRoute: MedicalStockSettingStockRoute,
}

const MedicalStockRouteWithChildren = MedicalStockRoute._addFileChildren(
  MedicalStockRouteChildren,
)

interface NurseRouteChildren {
  NurseChecklistRoute: typeof NurseChecklistRoute
  NurseDashboardNurseRoute: typeof NurseDashboardNurseRoute
  NurseFichePatientRoute: typeof NurseFichePatientRoute
  NursePatientMedecineRoute: typeof NursePatientMedecineRoute
  NurseReportNurseRoute: typeof NurseReportNurseRoute
  NurseSettingNurseRoute: typeof NurseSettingNurseRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseChecklistRoute: NurseChecklistRoute,
  NurseDashboardNurseRoute: NurseDashboardNurseRoute,
  NurseFichePatientRoute: NurseFichePatientRoute,
  NursePatientMedecineRoute: NursePatientMedecineRoute,
  NurseReportNurseRoute: NurseReportNurseRoute,
  NurseSettingNurseRoute: NurseSettingNurseRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface OpdRouteChildren {
  OpdBirthRegistrationRoute: typeof OpdBirthRegistrationRoute
  OpdCertificateRoute: typeof OpdCertificateRoute
  OpdDayCareRoute: typeof OpdDayCareRoute
  OpdInvestigationOpdRoute: typeof OpdInvestigationOpdRoute
  OpdMessageOpdRoute: typeof OpdMessageOpdRoute
  OpdProfilOpdRoute: typeof OpdProfilOpdRoute
  OpdQueueRoute: typeof OpdQueueRoute
  OpdRegistrationOpdRoute: typeof OpdRegistrationOpdRoute
  OpdRevisitRoute: typeof OpdRevisitRoute
  OpdSettingOpdRoute: typeof OpdSettingOpdRoute
  OpdVaccinRoute: typeof OpdVaccinRoute
}

const OpdRouteChildren: OpdRouteChildren = {
  OpdBirthRegistrationRoute: OpdBirthRegistrationRoute,
  OpdCertificateRoute: OpdCertificateRoute,
  OpdDayCareRoute: OpdDayCareRoute,
  OpdInvestigationOpdRoute: OpdInvestigationOpdRoute,
  OpdMessageOpdRoute: OpdMessageOpdRoute,
  OpdProfilOpdRoute: OpdProfilOpdRoute,
  OpdQueueRoute: OpdQueueRoute,
  OpdRegistrationOpdRoute: OpdRegistrationOpdRoute,
  OpdRevisitRoute: OpdRevisitRoute,
  OpdSettingOpdRoute: OpdSettingOpdRoute,
  OpdVaccinRoute: OpdVaccinRoute,
}

const OpdRouteWithChildren = OpdRoute._addFileChildren(OpdRouteChildren)

interface RadiologyRouteChildren {
  RadiologyRadiologyRoute: typeof RadiologyRadiologyRoute
}

const RadiologyRouteChildren: RadiologyRouteChildren = {
  RadiologyRadiologyRoute: RadiologyRadiologyRoute,
}

const RadiologyRouteWithChildren = RadiologyRoute._addFileChildren(
  RadiologyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof RadiologyRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/dashboard-appointment': typeof AppointmentsDashboardAppointmentRoute
  '/message-appointment': typeof AppointmentsMessageAppointmentRoute
  '/priseAppointment': typeof AppointmentsPriseAppointmentRoute
  '/profil-appointment': typeof AppointmentsProfilAppointmentRoute
  '/setting-appointment': typeof AppointmentsSettingAppointmentRoute
  '/suiviAppointment': typeof AppointmentsSuiviAppointmentRoute
  '/appointment-doctor': typeof DoctorAppointmentDoctorRoute
  '/dashboard-doctor': typeof DoctorDashboardDoctorRoute
  '/message-doctor': typeof DoctorMessageDoctorRoute
  '/ordonnance': typeof DoctorOrdonnanceRoute
  '/patient-doctor': typeof DoctorPatientDoctorRoute
  '/profil-doctor': typeof DoctorProfilDoctorRoute
  '/setting-doctor': typeof DoctorSettingDoctorRoute
  '/dashboard': typeof HomeDashboardRoute
  '/message': typeof HomeMessageRoute
  '/patient': typeof HomePatientRoute
  '/personnel': typeof HomePersonnelRoute
  '/profil': typeof HomeProfilRoute
  '/report': typeof HomeReportRoute
  '/service': typeof HomeServiceRoute
  '/setting': typeof HomeSettingRoute
  '/discharge': typeof IpdDischargeRoute
  '/investigation': typeof IpdInvestigationRoute
  '/ipd': typeof IpdIpdRoute
  '/medecines': typeof IpdMedecinesRoute
  '/oT': typeof IpdOTRoute
  '/payment': typeof IpdPaymentRoute
  '/registration-ipd': typeof IpdRegistrationIpdRoute
  '/report-ipd': typeof IpdReportIpdRoute
  '/ipd-request': typeof LabIpdRequestRoute
  '/opd-request': typeof LabOpdRequestRoute
  '/report-lab': typeof LabReportLabRoute
  '/setting-lab': typeof LabSettingLabRoute
  '/administration': typeof MedicalStockAdministrationRoute
  '/approvisionnement': typeof MedicalStockApprovisionnementRoute
  '/article': typeof MedicalStockArticleRoute
  '/commande': typeof MedicalStockCommandeRoute
  '/dashboard-stock': typeof MedicalStockDashboardStockRoute
  '/inventaire': typeof MedicalStockInventaireRoute
  '/maintenance': typeof MedicalStockMaintenanceRoute
  '/message-stock': typeof MedicalStockMessageStockRoute
  '/profil-stock': typeof MedicalStockProfilStockRoute
  '/setting-stock': typeof MedicalStockSettingStockRoute
  '/checklist': typeof NurseChecklistRoute
  '/dashboard-nurse': typeof NurseDashboardNurseRoute
  '/fiche-patient': typeof NurseFichePatientRoute
  '/patient-medecine': typeof NursePatientMedecineRoute
  '/report-nurse': typeof NurseReportNurseRoute
  '/setting-nurse': typeof NurseSettingNurseRoute
  '/birth-registration': typeof OpdBirthRegistrationRoute
  '/certificate': typeof OpdCertificateRoute
  '/dayCare': typeof OpdDayCareRoute
  '/investigation-opd': typeof OpdInvestigationOpdRoute
  '/message-opd': typeof OpdMessageOpdRoute
  '/profil-opd': typeof OpdProfilOpdRoute
  '/queue': typeof OpdQueueRoute
  '/registration-opd': typeof OpdRegistrationOpdRoute
  '/revisit': typeof OpdRevisitRoute
  '/setting-opd': typeof OpdSettingOpdRoute
  '/vaccin': typeof OpdVaccinRoute
  '/radiology': typeof RadiologyRadiologyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof RadiologyRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/dashboard-appointment': typeof AppointmentsDashboardAppointmentRoute
  '/message-appointment': typeof AppointmentsMessageAppointmentRoute
  '/priseAppointment': typeof AppointmentsPriseAppointmentRoute
  '/profil-appointment': typeof AppointmentsProfilAppointmentRoute
  '/setting-appointment': typeof AppointmentsSettingAppointmentRoute
  '/suiviAppointment': typeof AppointmentsSuiviAppointmentRoute
  '/appointment-doctor': typeof DoctorAppointmentDoctorRoute
  '/dashboard-doctor': typeof DoctorDashboardDoctorRoute
  '/message-doctor': typeof DoctorMessageDoctorRoute
  '/ordonnance': typeof DoctorOrdonnanceRoute
  '/patient-doctor': typeof DoctorPatientDoctorRoute
  '/profil-doctor': typeof DoctorProfilDoctorRoute
  '/setting-doctor': typeof DoctorSettingDoctorRoute
  '/dashboard': typeof HomeDashboardRoute
  '/message': typeof HomeMessageRoute
  '/patient': typeof HomePatientRoute
  '/personnel': typeof HomePersonnelRoute
  '/profil': typeof HomeProfilRoute
  '/report': typeof HomeReportRoute
  '/service': typeof HomeServiceRoute
  '/setting': typeof HomeSettingRoute
  '/discharge': typeof IpdDischargeRoute
  '/investigation': typeof IpdInvestigationRoute
  '/ipd': typeof IpdIpdRoute
  '/medecines': typeof IpdMedecinesRoute
  '/oT': typeof IpdOTRoute
  '/payment': typeof IpdPaymentRoute
  '/registration-ipd': typeof IpdRegistrationIpdRoute
  '/report-ipd': typeof IpdReportIpdRoute
  '/ipd-request': typeof LabIpdRequestRoute
  '/opd-request': typeof LabOpdRequestRoute
  '/report-lab': typeof LabReportLabRoute
  '/setting-lab': typeof LabSettingLabRoute
  '/administration': typeof MedicalStockAdministrationRoute
  '/approvisionnement': typeof MedicalStockApprovisionnementRoute
  '/article': typeof MedicalStockArticleRoute
  '/commande': typeof MedicalStockCommandeRoute
  '/dashboard-stock': typeof MedicalStockDashboardStockRoute
  '/inventaire': typeof MedicalStockInventaireRoute
  '/maintenance': typeof MedicalStockMaintenanceRoute
  '/message-stock': typeof MedicalStockMessageStockRoute
  '/profil-stock': typeof MedicalStockProfilStockRoute
  '/setting-stock': typeof MedicalStockSettingStockRoute
  '/checklist': typeof NurseChecklistRoute
  '/dashboard-nurse': typeof NurseDashboardNurseRoute
  '/fiche-patient': typeof NurseFichePatientRoute
  '/patient-medecine': typeof NursePatientMedecineRoute
  '/report-nurse': typeof NurseReportNurseRoute
  '/setting-nurse': typeof NurseSettingNurseRoute
  '/birth-registration': typeof OpdBirthRegistrationRoute
  '/certificate': typeof OpdCertificateRoute
  '/dayCare': typeof OpdDayCareRoute
  '/investigation-opd': typeof OpdInvestigationOpdRoute
  '/message-opd': typeof OpdMessageOpdRoute
  '/profil-opd': typeof OpdProfilOpdRoute
  '/queue': typeof OpdQueueRoute
  '/registration-opd': typeof OpdRegistrationOpdRoute
  '/revisit': typeof OpdRevisitRoute
  '/setting-opd': typeof OpdSettingOpdRoute
  '/vaccin': typeof OpdVaccinRoute
  '/radiology': typeof RadiologyRadiologyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_appointments': typeof AppointmentsRouteWithChildren
  '/_doctor': typeof DoctorRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_ipd': typeof IpdRouteWithChildren
  '/_lab': typeof LabRouteWithChildren
  '/_medical-stock': typeof MedicalStockRouteWithChildren
  '/_nurse': typeof NurseRouteWithChildren
  '/_opd': typeof OpdRouteWithChildren
  '/_radiology': typeof RadiologyRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-principal': typeof MenuPrincipalRoute
  '/_appointments/dashboard-appointment': typeof AppointmentsDashboardAppointmentRoute
  '/_appointments/message-appointment': typeof AppointmentsMessageAppointmentRoute
  '/_appointments/priseAppointment': typeof AppointmentsPriseAppointmentRoute
  '/_appointments/profil-appointment': typeof AppointmentsProfilAppointmentRoute
  '/_appointments/setting-appointment': typeof AppointmentsSettingAppointmentRoute
  '/_appointments/suiviAppointment': typeof AppointmentsSuiviAppointmentRoute
  '/_doctor/appointment-doctor': typeof DoctorAppointmentDoctorRoute
  '/_doctor/dashboard-doctor': typeof DoctorDashboardDoctorRoute
  '/_doctor/message-doctor': typeof DoctorMessageDoctorRoute
  '/_doctor/ordonnance': typeof DoctorOrdonnanceRoute
  '/_doctor/patient-doctor': typeof DoctorPatientDoctorRoute
  '/_doctor/profil-doctor': typeof DoctorProfilDoctorRoute
  '/_doctor/setting-doctor': typeof DoctorSettingDoctorRoute
  '/_home/dashboard': typeof HomeDashboardRoute
  '/_home/message': typeof HomeMessageRoute
  '/_home/patient': typeof HomePatientRoute
  '/_home/personnel': typeof HomePersonnelRoute
  '/_home/profil': typeof HomeProfilRoute
  '/_home/report': typeof HomeReportRoute
  '/_home/service': typeof HomeServiceRoute
  '/_home/setting': typeof HomeSettingRoute
  '/_ipd/discharge': typeof IpdDischargeRoute
  '/_ipd/investigation': typeof IpdInvestigationRoute
  '/_ipd/ipd': typeof IpdIpdRoute
  '/_ipd/medecines': typeof IpdMedecinesRoute
  '/_ipd/oT': typeof IpdOTRoute
  '/_ipd/payment': typeof IpdPaymentRoute
  '/_ipd/registration-ipd': typeof IpdRegistrationIpdRoute
  '/_ipd/report-ipd': typeof IpdReportIpdRoute
  '/_lab/ipd-request': typeof LabIpdRequestRoute
  '/_lab/opd-request': typeof LabOpdRequestRoute
  '/_lab/report-lab': typeof LabReportLabRoute
  '/_lab/setting-lab': typeof LabSettingLabRoute
  '/_medical-stock/administration': typeof MedicalStockAdministrationRoute
  '/_medical-stock/approvisionnement': typeof MedicalStockApprovisionnementRoute
  '/_medical-stock/article': typeof MedicalStockArticleRoute
  '/_medical-stock/commande': typeof MedicalStockCommandeRoute
  '/_medical-stock/dashboard-stock': typeof MedicalStockDashboardStockRoute
  '/_medical-stock/inventaire': typeof MedicalStockInventaireRoute
  '/_medical-stock/maintenance': typeof MedicalStockMaintenanceRoute
  '/_medical-stock/message-stock': typeof MedicalStockMessageStockRoute
  '/_medical-stock/profil-stock': typeof MedicalStockProfilStockRoute
  '/_medical-stock/setting-stock': typeof MedicalStockSettingStockRoute
  '/_nurse/checklist': typeof NurseChecklistRoute
  '/_nurse/dashboard-nurse': typeof NurseDashboardNurseRoute
  '/_nurse/fiche-patient': typeof NurseFichePatientRoute
  '/_nurse/patient-medecine': typeof NursePatientMedecineRoute
  '/_nurse/report-nurse': typeof NurseReportNurseRoute
  '/_nurse/setting-nurse': typeof NurseSettingNurseRoute
  '/_opd/birth-registration': typeof OpdBirthRegistrationRoute
  '/_opd/certificate': typeof OpdCertificateRoute
  '/_opd/dayCare': typeof OpdDayCareRoute
  '/_opd/investigation-opd': typeof OpdInvestigationOpdRoute
  '/_opd/message-opd': typeof OpdMessageOpdRoute
  '/_opd/profil-opd': typeof OpdProfilOpdRoute
  '/_opd/queue': typeof OpdQueueRoute
  '/_opd/registration-opd': typeof OpdRegistrationOpdRoute
  '/_opd/revisit': typeof OpdRevisitRoute
  '/_opd/setting-opd': typeof OpdSettingOpdRoute
  '/_opd/vaccin': typeof OpdVaccinRoute
  '/_radiology/radiology': typeof RadiologyRadiologyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/menu-principal'
    | '/dashboard-appointment'
    | '/message-appointment'
    | '/priseAppointment'
    | '/profil-appointment'
    | '/setting-appointment'
    | '/suiviAppointment'
    | '/appointment-doctor'
    | '/dashboard-doctor'
    | '/message-doctor'
    | '/ordonnance'
    | '/patient-doctor'
    | '/profil-doctor'
    | '/setting-doctor'
    | '/dashboard'
    | '/message'
    | '/patient'
    | '/personnel'
    | '/profil'
    | '/report'
    | '/service'
    | '/setting'
    | '/discharge'
    | '/investigation'
    | '/ipd'
    | '/medecines'
    | '/oT'
    | '/payment'
    | '/registration-ipd'
    | '/report-ipd'
    | '/ipd-request'
    | '/opd-request'
    | '/report-lab'
    | '/setting-lab'
    | '/administration'
    | '/approvisionnement'
    | '/article'
    | '/commande'
    | '/dashboard-stock'
    | '/inventaire'
    | '/maintenance'
    | '/message-stock'
    | '/profil-stock'
    | '/setting-stock'
    | '/checklist'
    | '/dashboard-nurse'
    | '/fiche-patient'
    | '/patient-medecine'
    | '/report-nurse'
    | '/setting-nurse'
    | '/birth-registration'
    | '/certificate'
    | '/dayCare'
    | '/investigation-opd'
    | '/message-opd'
    | '/profil-opd'
    | '/queue'
    | '/registration-opd'
    | '/revisit'
    | '/setting-opd'
    | '/vaccin'
    | '/radiology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/menu-principal'
    | '/dashboard-appointment'
    | '/message-appointment'
    | '/priseAppointment'
    | '/profil-appointment'
    | '/setting-appointment'
    | '/suiviAppointment'
    | '/appointment-doctor'
    | '/dashboard-doctor'
    | '/message-doctor'
    | '/ordonnance'
    | '/patient-doctor'
    | '/profil-doctor'
    | '/setting-doctor'
    | '/dashboard'
    | '/message'
    | '/patient'
    | '/personnel'
    | '/profil'
    | '/report'
    | '/service'
    | '/setting'
    | '/discharge'
    | '/investigation'
    | '/ipd'
    | '/medecines'
    | '/oT'
    | '/payment'
    | '/registration-ipd'
    | '/report-ipd'
    | '/ipd-request'
    | '/opd-request'
    | '/report-lab'
    | '/setting-lab'
    | '/administration'
    | '/approvisionnement'
    | '/article'
    | '/commande'
    | '/dashboard-stock'
    | '/inventaire'
    | '/maintenance'
    | '/message-stock'
    | '/profil-stock'
    | '/setting-stock'
    | '/checklist'
    | '/dashboard-nurse'
    | '/fiche-patient'
    | '/patient-medecine'
    | '/report-nurse'
    | '/setting-nurse'
    | '/birth-registration'
    | '/certificate'
    | '/dayCare'
    | '/investigation-opd'
    | '/message-opd'
    | '/profil-opd'
    | '/queue'
    | '/registration-opd'
    | '/revisit'
    | '/setting-opd'
    | '/vaccin'
    | '/radiology'
  id:
    | '__root__'
    | '/'
    | '/_appointments'
    | '/_doctor'
    | '/_home'
    | '/_ipd'
    | '/_lab'
    | '/_medical-stock'
    | '/_nurse'
    | '/_opd'
    | '/_radiology'
    | '/login'
    | '/menu-principal'
    | '/_appointments/dashboard-appointment'
    | '/_appointments/message-appointment'
    | '/_appointments/priseAppointment'
    | '/_appointments/profil-appointment'
    | '/_appointments/setting-appointment'
    | '/_appointments/suiviAppointment'
    | '/_doctor/appointment-doctor'
    | '/_doctor/dashboard-doctor'
    | '/_doctor/message-doctor'
    | '/_doctor/ordonnance'
    | '/_doctor/patient-doctor'
    | '/_doctor/profil-doctor'
    | '/_doctor/setting-doctor'
    | '/_home/dashboard'
    | '/_home/message'
    | '/_home/patient'
    | '/_home/personnel'
    | '/_home/profil'
    | '/_home/report'
    | '/_home/service'
    | '/_home/setting'
    | '/_ipd/discharge'
    | '/_ipd/investigation'
    | '/_ipd/ipd'
    | '/_ipd/medecines'
    | '/_ipd/oT'
    | '/_ipd/payment'
    | '/_ipd/registration-ipd'
    | '/_ipd/report-ipd'
    | '/_lab/ipd-request'
    | '/_lab/opd-request'
    | '/_lab/report-lab'
    | '/_lab/setting-lab'
    | '/_medical-stock/administration'
    | '/_medical-stock/approvisionnement'
    | '/_medical-stock/article'
    | '/_medical-stock/commande'
    | '/_medical-stock/dashboard-stock'
    | '/_medical-stock/inventaire'
    | '/_medical-stock/maintenance'
    | '/_medical-stock/message-stock'
    | '/_medical-stock/profil-stock'
    | '/_medical-stock/setting-stock'
    | '/_nurse/checklist'
    | '/_nurse/dashboard-nurse'
    | '/_nurse/fiche-patient'
    | '/_nurse/patient-medecine'
    | '/_nurse/report-nurse'
    | '/_nurse/setting-nurse'
    | '/_opd/birth-registration'
    | '/_opd/certificate'
    | '/_opd/dayCare'
    | '/_opd/investigation-opd'
    | '/_opd/message-opd'
    | '/_opd/profil-opd'
    | '/_opd/queue'
    | '/_opd/registration-opd'
    | '/_opd/revisit'
    | '/_opd/setting-opd'
    | '/_opd/vaccin'
    | '/_radiology/radiology'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  IpdRoute: typeof IpdRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  MedicalStockRoute: typeof MedicalStockRouteWithChildren
  NurseRoute: typeof NurseRouteWithChildren
  OpdRoute: typeof OpdRouteWithChildren
  RadiologyRoute: typeof RadiologyRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuPrincipalRoute: typeof MenuPrincipalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  IpdRoute: IpdRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  MedicalStockRoute: MedicalStockRouteWithChildren,
  NurseRoute: NurseRouteWithChildren,
  OpdRoute: OpdRouteWithChildren,
  RadiologyRoute: RadiologyRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuPrincipalRoute: MenuPrincipalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_appointments",
        "/_doctor",
        "/_home",
        "/_ipd",
        "/_lab",
        "/_medical-stock",
        "/_nurse",
        "/_opd",
        "/_radiology",
        "/login",
        "/menu-principal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_appointments": {
      "filePath": "_appointments.tsx",
      "children": [
        "/_appointments/dashboard-appointment",
        "/_appointments/message-appointment",
        "/_appointments/priseAppointment",
        "/_appointments/profil-appointment",
        "/_appointments/setting-appointment",
        "/_appointments/suiviAppointment"
      ]
    },
    "/_doctor": {
      "filePath": "_doctor.tsx",
      "children": [
        "/_doctor/appointment-doctor",
        "/_doctor/dashboard-doctor",
        "/_doctor/message-doctor",
        "/_doctor/ordonnance",
        "/_doctor/patient-doctor",
        "/_doctor/profil-doctor",
        "/_doctor/setting-doctor"
      ]
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/dashboard",
        "/_home/message",
        "/_home/patient",
        "/_home/personnel",
        "/_home/profil",
        "/_home/report",
        "/_home/service",
        "/_home/setting"
      ]
    },
    "/_ipd": {
      "filePath": "_ipd.tsx",
      "children": [
        "/_ipd/discharge",
        "/_ipd/investigation",
        "/_ipd/ipd",
        "/_ipd/medecines",
        "/_ipd/oT",
        "/_ipd/payment",
        "/_ipd/registration-ipd",
        "/_ipd/report-ipd"
      ]
    },
    "/_lab": {
      "filePath": "_lab.tsx",
      "children": [
        "/_lab/ipd-request",
        "/_lab/opd-request",
        "/_lab/report-lab",
        "/_lab/setting-lab"
      ]
    },
    "/_medical-stock": {
      "filePath": "_medical-stock.tsx",
      "children": [
        "/_medical-stock/administration",
        "/_medical-stock/approvisionnement",
        "/_medical-stock/article",
        "/_medical-stock/commande",
        "/_medical-stock/dashboard-stock",
        "/_medical-stock/inventaire",
        "/_medical-stock/maintenance",
        "/_medical-stock/message-stock",
        "/_medical-stock/profil-stock",
        "/_medical-stock/setting-stock"
      ]
    },
    "/_nurse": {
      "filePath": "_nurse.tsx",
      "children": [
        "/_nurse/checklist",
        "/_nurse/dashboard-nurse",
        "/_nurse/fiche-patient",
        "/_nurse/patient-medecine",
        "/_nurse/report-nurse",
        "/_nurse/setting-nurse"
      ]
    },
    "/_opd": {
      "filePath": "_opd.tsx",
      "children": [
        "/_opd/birth-registration",
        "/_opd/certificate",
        "/_opd/dayCare",
        "/_opd/investigation-opd",
        "/_opd/message-opd",
        "/_opd/profil-opd",
        "/_opd/queue",
        "/_opd/registration-opd",
        "/_opd/revisit",
        "/_opd/setting-opd",
        "/_opd/vaccin"
      ]
    },
    "/_radiology": {
      "filePath": "_radiology.tsx",
      "children": [
        "/_radiology/radiology"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/menu-principal": {
      "filePath": "menu-principal.tsx"
    },
    "/_appointments/dashboard-appointment": {
      "filePath": "_appointments/dashboard-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/message-appointment": {
      "filePath": "_appointments/message-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/priseAppointment": {
      "filePath": "_appointments/priseAppointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/profil-appointment": {
      "filePath": "_appointments/profil-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/setting-appointment": {
      "filePath": "_appointments/setting-appointment.tsx",
      "parent": "/_appointments"
    },
    "/_appointments/suiviAppointment": {
      "filePath": "_appointments/suiviAppointment.tsx",
      "parent": "/_appointments"
    },
    "/_doctor/appointment-doctor": {
      "filePath": "_doctor/appointment-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/dashboard-doctor": {
      "filePath": "_doctor/dashboard-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/message-doctor": {
      "filePath": "_doctor/message-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/ordonnance": {
      "filePath": "_doctor/ordonnance.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/patient-doctor": {
      "filePath": "_doctor/patient-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/profil-doctor": {
      "filePath": "_doctor/profil-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_doctor/setting-doctor": {
      "filePath": "_doctor/setting-doctor.tsx",
      "parent": "/_doctor"
    },
    "/_home/dashboard": {
      "filePath": "_home/dashboard.tsx",
      "parent": "/_home"
    },
    "/_home/message": {
      "filePath": "_home/message.tsx",
      "parent": "/_home"
    },
    "/_home/patient": {
      "filePath": "_home/patient.tsx",
      "parent": "/_home"
    },
    "/_home/personnel": {
      "filePath": "_home/personnel.tsx",
      "parent": "/_home"
    },
    "/_home/profil": {
      "filePath": "_home/profil.tsx",
      "parent": "/_home"
    },
    "/_home/report": {
      "filePath": "_home/report.tsx",
      "parent": "/_home"
    },
    "/_home/service": {
      "filePath": "_home/service.tsx",
      "parent": "/_home"
    },
    "/_home/setting": {
      "filePath": "_home/setting.tsx",
      "parent": "/_home"
    },
    "/_ipd/discharge": {
      "filePath": "_ipd/discharge.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/investigation": {
      "filePath": "_ipd/investigation.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/ipd": {
      "filePath": "_ipd/ipd.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/medecines": {
      "filePath": "_ipd/medecines.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/oT": {
      "filePath": "_ipd/oT.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/payment": {
      "filePath": "_ipd/payment.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/registration-ipd": {
      "filePath": "_ipd/registration-ipd.tsx",
      "parent": "/_ipd"
    },
    "/_ipd/report-ipd": {
      "filePath": "_ipd/report-ipd.tsx",
      "parent": "/_ipd"
    },
    "/_lab/ipd-request": {
      "filePath": "_lab/ipd-request.tsx",
      "parent": "/_lab"
    },
    "/_lab/opd-request": {
      "filePath": "_lab/opd-request.tsx",
      "parent": "/_lab"
    },
    "/_lab/report-lab": {
      "filePath": "_lab/report-lab.tsx",
      "parent": "/_lab"
    },
    "/_lab/setting-lab": {
      "filePath": "_lab/setting-lab.tsx",
      "parent": "/_lab"
    },
    "/_medical-stock/administration": {
      "filePath": "_medical-stock/administration.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/approvisionnement": {
      "filePath": "_medical-stock/approvisionnement.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/article": {
      "filePath": "_medical-stock/article.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/commande": {
      "filePath": "_medical-stock/commande.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/dashboard-stock": {
      "filePath": "_medical-stock/dashboard-stock.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/inventaire": {
      "filePath": "_medical-stock/inventaire.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/maintenance": {
      "filePath": "_medical-stock/maintenance.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/message-stock": {
      "filePath": "_medical-stock/message-stock.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/profil-stock": {
      "filePath": "_medical-stock/profil-stock.tsx",
      "parent": "/_medical-stock"
    },
    "/_medical-stock/setting-stock": {
      "filePath": "_medical-stock/setting-stock.tsx",
      "parent": "/_medical-stock"
    },
    "/_nurse/checklist": {
      "filePath": "_nurse/checklist.tsx",
      "parent": "/_nurse"
    },
    "/_nurse/dashboard-nurse": {
      "filePath": "_nurse/dashboard-nurse.tsx",
      "parent": "/_nurse"
    },
    "/_nurse/fiche-patient": {
      "filePath": "_nurse/fiche-patient.tsx",
      "parent": "/_nurse"
    },
    "/_nurse/patient-medecine": {
      "filePath": "_nurse/patient-medecine.tsx",
      "parent": "/_nurse"
    },
    "/_nurse/report-nurse": {
      "filePath": "_nurse/report-nurse.tsx",
      "parent": "/_nurse"
    },
    "/_nurse/setting-nurse": {
      "filePath": "_nurse/setting-nurse.tsx",
      "parent": "/_nurse"
    },
    "/_opd/birth-registration": {
      "filePath": "_opd/birth-registration.tsx",
      "parent": "/_opd"
    },
    "/_opd/certificate": {
      "filePath": "_opd/certificate.tsx",
      "parent": "/_opd"
    },
    "/_opd/dayCare": {
      "filePath": "_opd/dayCare.tsx",
      "parent": "/_opd"
    },
    "/_opd/investigation-opd": {
      "filePath": "_opd/investigation-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/message-opd": {
      "filePath": "_opd/message-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/profil-opd": {
      "filePath": "_opd/profil-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/queue": {
      "filePath": "_opd/queue.tsx",
      "parent": "/_opd"
    },
    "/_opd/registration-opd": {
      "filePath": "_opd/registration-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/revisit": {
      "filePath": "_opd/revisit.tsx",
      "parent": "/_opd"
    },
    "/_opd/setting-opd": {
      "filePath": "_opd/setting-opd.tsx",
      "parent": "/_opd"
    },
    "/_opd/vaccin": {
      "filePath": "_opd/vaccin.tsx",
      "parent": "/_opd"
    },
    "/_radiology/radiology": {
      "filePath": "_radiology/radiology.tsx",
      "parent": "/_radiology"
    }
  }
}
ROUTE_MANIFEST_END */
